package sdk

import (
	"fmt"
	"strings"

	"github.com/bakhod1r/spector/internal/core"
)

// generateCSharp renders one self-contained Client.cs: a class per schema and a
// Client with a typed method per operation, on HttpClient and System.Text.Json
// alone. Properties are PascalCase with a [JsonPropertyName] so the wire JSON
// keeps its original key names while the C# surface stays idiomatic. Targets
// .NET 8 with nullable reference types enabled; no external dependency.
func generateCSharp(doc *core.Document, opts Options) ([]File, error) {
	var b strings.Builder

	ns := opts.Package
	if ns == "" {
		ns = "ApiClient"
	}

	b.WriteString("// Code generated by specter. Edit freely — it is yours now.\n")
	b.WriteString("#nullable enable\n\n")
	b.WriteString("using System;\n")
	b.WriteString("using System.Collections.Generic;\n")
	b.WriteString("using System.Net.Http;\n")
	b.WriteString("using System.Text;\n")
	b.WriteString("using System.Text.Json;\n")
	b.WriteString("using System.Text.Json.Serialization;\n")
	b.WriteString("using System.Threading.Tasks;\n\n")

	fmt.Fprintf(&b, "namespace %s;\n\n", ns)

	for _, name := range sortedSchemaNames(doc) {
		writeCSharpClass(&b, doc, name, doc.Components.Schemas[name])
	}

	// A non-2xx response, with the body kept for inspection.
	b.WriteString(`/// <summary>A non-2xx response. The body, if any, is kept for inspection.</summary>
public class ApiException : Exception
{
    public int Status { get; }
    public string? Body { get; }

    public ApiException(int status, string? body)
        : base($"request failed: {status}")
    {
        Status = status;
        Body = body;
    }
}

`)

	// The Client: one private RequestAsync helper every operation funnels through.
	fmt.Fprintf(&b, `/// <summary>Typed client for the API. Pass a baseUrl, and a token when the API
/// authenticates with a bearer scheme.</summary>
public class Client
{
    private readonly string _baseUrl;
    private readonly string? _token;
    private readonly HttpClient _http;

    private static readonly JsonSerializerOptions _json = new()
    {
        PropertyNameCaseInsensitive = true,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    };

    public Client(string baseUrl = %q, string? token = null, HttpClient? http = null)
    {
        _baseUrl = baseUrl.TrimEnd('/');
        _token = token;
        _http = http ?? new HttpClient();
    }

    private async System.Threading.Tasks.Task<T?> RequestAsync<T>(HttpMethod method, string path, IDictionary<string, object?>? query, object? body)
    {
        var url = _baseUrl + path;
        if (query != null)
        {
            var parts = new List<string>();
            foreach (var kv in query)
            {
                if (kv.Value == null) continue;
                parts.Add(Uri.EscapeDataString(kv.Key) + "=" + Uri.EscapeDataString(kv.Value.ToString() ?? ""));
            }
            if (parts.Count > 0) url += "?" + string.Join("&", parts);
        }

        using var req = new HttpRequestMessage(method, url);
        if (_token != null)
            req.Headers.TryAddWithoutValidation("Authorization", "Bearer " + _token);
        if (body != null)
        {
            var payload = JsonSerializer.Serialize(body, _json);
            req.Content = new StringContent(payload, Encoding.UTF8, "application/json");
        }

        using var res = await _http.SendAsync(req).ConfigureAwait(false);
        var text = await res.Content.ReadAsStringAsync().ConfigureAwait(false);
        if (!res.IsSuccessStatusCode)
            throw new ApiException((int)res.StatusCode, string.IsNullOrEmpty(text) ? null : text);
        if (string.IsNullOrEmpty(text))
            return default;
        return JsonSerializer.Deserialize<T>(text, _json);
    }
`, opts.BaseURL)

	for _, op := range flatten(doc) {
		writeCSharpMethod(&b, op)
	}

	b.WriteString("}\n")
	return []File{{Name: "Client.cs", Data: []byte(b.String())}}, nil
}

func writeCSharpClass(b *strings.Builder, doc *core.Document, name string, s *core.Schema) {
	if s == nil {
		return
	}
	typeName := pascalCase(name)
	// An alias or non-object schema needs no class in C#; callers use the mapped
	// primitive/collection directly. A short comment records the intent, mirroring
	// how the other emitters handle these.
	if a := aliasTarget(s); a != nil {
		fmt.Fprintf(b, "// %s is an alias for %s.\n\n", typeName, csType(a))
		return
	}
	if !isStruct(s) {
		fmt.Fprintf(b, "// %s is %s.\n\n", typeName, csType(s))
		return
	}

	fields := resolvedFields(doc, s)
	fmt.Fprintf(b, "public class %s\n{\n", typeName)
	for _, f := range fields {
		fmt.Fprintf(b, "    [JsonPropertyName(%q)]\n", f.Name)
		fmt.Fprintf(b, "    public %s? %s { get; set; }\n", csType(f.Schema), csPropName(f.Name))
	}
	b.WriteString("}\n\n")
}

func writeCSharpMethod(b *strings.Builder, op operation) {
	var params []string
	for _, p := range op.PathParams {
		params = append(params, "string "+csParamName(p))
	}
	if op.Body != nil {
		params = append(params, csType(op.Body)+" body")
	}
	if len(op.Query) > 0 {
		params = append(params, "IDictionary<string, object?>? query = null")
	}

	result := ""
	if op.Result != nil {
		result = csType(op.Result)
	}
	// Fully qualify Task so a schema named "Task" (the API can have one) cannot
	// shadow System.Threading.Tasks.Task in the method's return position.
	ret := "System.Threading.Tasks.Task"
	if result != "" {
		ret = fmt.Sprintf("System.Threading.Tasks.Task<%s?>", result)
	}

	b.WriteString("\n")
	if op.Summary != "" {
		fmt.Fprintf(b, "    /// <summary>%s</summary>\n", op.Summary)
	}
	if op.Deprecated {
		fmt.Fprintf(b, "    [Obsolete(\"the API marks this operation deprecated\")]\n")
	}
	fmt.Fprintf(b, "    public %s %s(%s)\n    {\n", ret, pascalCase(op.Name), strings.Join(params, ", "))

	path := op.Path
	for _, p := range op.PathParams {
		path = strings.ReplaceAll(path, "{"+p+"}", "{"+csParamName(p)+"}")
	}
	fmt.Fprintf(b, "        var path = $%q;\n", path)

	query := "null"
	if len(op.Query) > 0 {
		query = "query"
	}
	body := "null"
	if op.Body != nil {
		body = "body"
	}

	method := fmt.Sprintf("new HttpMethod(%q)", op.Method)
	if result == "" {
		// A bodiless operation still needs a type argument for the helper; object
		// is discarded by the caller.
		fmt.Fprintf(b, "        return RequestAsync<object>(%s, path, %s, %s);\n", method, query, body)
	} else {
		fmt.Fprintf(b, "        return RequestAsync<%s>(%s, path, %s, %s);\n", result, method, query, body)
	}
	b.WriteString("    }\n")
}

// csType maps a JSON Schema fragment to a C# type expression.
func csType(s *core.Schema) string {
	if s == nil {
		return "object"
	}
	if s.Ref != "" {
		return pascalCase(refName(s.Ref))
	}
	switch s.Type {
	case "string":
		return "string"
	case "integer":
		return "long"
	case "number":
		return "double"
	case "boolean":
		return "bool"
	case "array":
		return "List<" + csType(s.Items) + ">"
	case "object":
		if s.AdditionalProperties != nil {
			return "Dictionary<string, " + csType(s.AdditionalProperties) + ">"
		}
		return "Dictionary<string, object>"
	}
	return "object"
}

// csPropName makes a wire key a legal, exported C# property name.
func csPropName(name string) string {
	n := pascalCase(name)
	if n == "" {
		return "Field"
	}
	if n[0] >= '0' && n[0] <= '9' {
		return "F" + n
	}
	return n
}

// csParamName makes a path parameter usable as a camelCase argument name,
// guarding the C# reserved words an identifier could collide with.
func csParamName(name string) string {
	n := camelCase(name)
	if n == "" {
		return "param"
	}
	if n[0] >= '0' && n[0] <= '9' {
		n = "p" + n
	}
	return csGuardKeyword(n)
}

// csGuardKeyword prefixes a C# reserved word with "@" so it stays a legal
// identifier.
func csGuardKeyword(n string) string {
	switch n {
	case "abstract", "as", "base", "bool", "break", "byte", "case", "catch",
		"char", "checked", "class", "const", "continue", "decimal", "default",
		"delegate", "do", "double", "else", "enum", "event", "explicit", "extern",
		"false", "finally", "fixed", "float", "for", "foreach", "goto", "if",
		"implicit", "in", "int", "interface", "internal", "is", "lock", "long",
		"namespace", "new", "null", "object", "operator", "out", "override",
		"params", "private", "protected", "public", "readonly", "ref", "return",
		"sbyte", "sealed", "short", "sizeof", "stackalloc", "static", "string",
		"struct", "switch", "this", "throw", "true", "try", "typeof", "uint",
		"ulong", "unchecked", "unsafe", "ushort", "using", "virtual", "void",
		"volatile", "while":
		return "@" + n
	}
	return n
}
