package sdk

import (
	"fmt"
	"go/format"
	"sort"
	"strings"

	"github.com/user/specter/internal/core"
)

// generateGo renders one self-contained client.go: a struct per schema and a
// Client with a typed method per operation, on net/http alone.
func generateGo(doc *core.Document, opts Options) ([]File, error) {
	var b strings.Builder

	fmt.Fprintf(&b, "// Code generated by specter. Edit freely — it is yours now.\n")
	fmt.Fprintf(&b, "package %s\n\n", opts.Package)
	b.WriteString(`import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

`)

	for _, name := range sortedSchemaNames(doc) {
		writeGoStruct(&b, name, doc.Components.Schemas[name])
	}

	fmt.Fprintf(&b, `// Client calls the API. The zero value is not usable; use New.
type Client struct {
	// BaseURL is the server every request is joined to.
	BaseURL string
	// Token, when set, is sent as "Authorization: Bearer <token>".
	Token string
	// HTTPClient defaults to http.DefaultClient.
	HTTPClient *http.Client
}

// New returns a Client for baseURL. Empty means the generated default (%q).
func New(baseURL string) *Client {
	if baseURL == "" {
		baseURL = %q
	}
	return &Client{BaseURL: baseURL, HTTPClient: http.DefaultClient}
}

// APIError is a non-2xx response, with the body kept for inspection.
type APIError struct {
	Status int
	Body   []byte
}

func (e *APIError) Error() string {
	return fmt.Sprintf("request failed: %%d: %%s", e.Status, e.Body)
}

func (c *Client) do(ctx context.Context, method, path string, query url.Values, body, out any) error {
	u := strings.TrimSuffix(c.BaseURL, "/") + path
	if len(query) > 0 {
		u += "?" + query.Encode()
	}
	var rd io.Reader
	if body != nil {
		data, err := json.Marshal(body)
		if err != nil {
			return err
		}
		rd = bytes.NewReader(data)
	}
	req, err := http.NewRequestWithContext(ctx, method, u, rd)
	if err != nil {
		return err
	}
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	if c.Token != "" {
		req.Header.Set("Authorization", "Bearer "+c.Token)
	}
	hc := c.HTTPClient
	if hc == nil {
		hc = http.DefaultClient
	}
	resp, err := hc.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	data, err := io.ReadAll(resp.Body)
	if err != nil {
		return err
	}
	if resp.StatusCode < 200 || resp.StatusCode > 299 {
		return &APIError{Status: resp.StatusCode, Body: data}
	}
	if out != nil && len(data) > 0 {
		return json.Unmarshal(data, out)
	}
	return nil
}
`, opts.BaseURL, opts.BaseURL)

	for _, op := range flatten(doc) {
		writeGoMethod(&b, op)
	}

	src := []byte(b.String())
	if formatted, err := format.Source(src); err == nil {
		src = formatted
	}
	// A failed format still returns the raw source: the error will surface as
	// a compile error in context, which beats hiding the output entirely.
	return []File{{Name: "client.go", Data: src}}, nil
}

func writeGoStruct(b *strings.Builder, name string, s *core.Schema) {
	if s == nil {
		return
	}
	typeName := exportName(name)
	if s.Type != "object" || len(s.Properties) == 0 {
		fmt.Fprintf(b, "type %s = %s\n\n", typeName, goType(s))
		return
	}
	fmt.Fprintf(b, "type %s struct {\n", typeName)
	props := make([]string, 0, len(s.Properties))
	for p := range s.Properties {
		props = append(props, p)
	}
	sort.Strings(props)
	required := map[string]bool{}
	for _, r := range s.Required {
		required[r] = true
	}
	for _, p := range props {
		tag := p
		if !required[p] {
			tag += ",omitempty"
		}
		fmt.Fprintf(b, "\t%s %s `json:%q`\n", exportName(p), goType(s.Properties[p]), tag)
	}
	fmt.Fprintf(b, "}\n\n")
}

func writeGoMethod(b *strings.Builder, op operation) {
	name := exportName(op.Name)

	var params []string
	params = append(params, "ctx context.Context")
	for _, p := range op.PathParams {
		params = append(params, fmt.Sprintf("%s string", goParamName(p)))
	}
	if op.Body != nil {
		params = append(params, "body "+goType(op.Body))
	}
	if len(op.Query) > 0 {
		params = append(params, "query url.Values")
	}

	result := ""
	if op.Result != nil {
		result = goType(op.Result)
	}

	b.WriteString("\n")
	if op.Summary != "" {
		fmt.Fprintf(b, "// %s %s\n", name, op.Summary)
	}
	if op.Deprecated {
		fmt.Fprintf(b, "//\n// Deprecated: the API marks this operation deprecated.\n")
	}

	ret := "error"
	if result != "" {
		ret = fmt.Sprintf("(%s, error)", result)
	}
	fmt.Fprintf(b, "func (c *Client) %s(%s) %s {\n", name, strings.Join(params, ", "), ret)

	path := op.Path
	var args []string
	for _, p := range op.PathParams {
		path = strings.ReplaceAll(path, "{"+p+"}", "%s")
		args = append(args, fmt.Sprintf("url.PathEscape(%s)", goParamName(p)))
	}
	if len(args) > 0 {
		fmt.Fprintf(b, "\tpath := fmt.Sprintf(%q, %s)\n", path, strings.Join(args, ", "))
	} else {
		fmt.Fprintf(b, "\tpath := %q\n", path)
	}

	query := "nil"
	if len(op.Query) > 0 {
		query = "query"
	}
	body := "nil"
	if op.Body != nil {
		body = "body"
	}

	if result == "" {
		fmt.Fprintf(b, "\treturn c.do(ctx, %q, path, %s, %s, nil)\n", op.Method, query, body)
	} else {
		fmt.Fprintf(b, "\tvar out %s\n", result)
		fmt.Fprintf(b, "\terr := c.do(ctx, %q, path, %s, %s, &out)\n", op.Method, query, body)
		fmt.Fprintf(b, "\treturn out, err\n")
	}
	fmt.Fprintf(b, "}\n")
}

// goType maps a JSON Schema fragment to a Go type expression.
func goType(s *core.Schema) string {
	if s == nil {
		return "any"
	}
	if s.Ref != "" {
		return exportName(refName(s.Ref))
	}
	switch s.Type {
	case "string":
		return "string"
	case "integer":
		return "int"
	case "number":
		return "float64"
	case "boolean":
		return "bool"
	case "array":
		return "[]" + goType(s.Items)
	case "object":
		if s.AdditionalProperties != nil {
			return "map[string]" + goType(s.AdditionalProperties)
		}
		return "map[string]any"
	}
	return "any"
}

// goParamName makes a path parameter a legal, unexported argument name.
func goParamName(name string) string {
	n := exportName(name)
	if n == "" {
		return "param"
	}
	n = strings.ToLower(n[:1]) + n[1:]
	// Guard the few likely collisions with identifiers the method builds.
	switch n {
	case "ctx", "body", "query", "path", "out", "err", "c":
		return n + "Param"
	}
	return n
}
