package sdk

import (
	"fmt"
	"strings"

	"github.com/user/specter/internal/core"
)

// generateJava renders a dependency-free Java 17 client. Java's standard
// library has no typed JSON binding, so this emits its own tiny JSON runtime
// (Json.java): a recursive-descent parser producing Map/List/Double/Boolean/
// String/null trees, and a serializer back to text. Every model is a record
// with fromJson/toJson that map wire keys to camelCase components, and the
// Client funnels each operation through java.net.http.HttpClient.
//
// javac requires each public top-level type in its own correctly named file,
// so the output is several File entries: Json.java, ApiException.java,
// Client.java, and one <Type>.java per struct schema. They share a package
// (opts.Package, or "apiclient") and compile together as one unit.
func generateJava(doc *core.Document, opts Options) ([]File, error) {
	pkg := opts.Package
	if pkg == "" {
		pkg = "apiclient"
	}

	var files []File
	files = append(files, File{Name: "Json.java", Data: []byte(javaJsonRuntime(pkg))})
	files = append(files, File{Name: "ApiException.java", Data: []byte(javaApiException(pkg))})

	// One record file per struct schema.
	for _, name := range sortedSchemaNames(doc) {
		s := doc.Components.Schemas[name]
		if s == nil || !isStruct(s) || aliasTarget(s) != nil {
			// Aliases and non-object schemas need no class: their referents
			// resolve straight to a Java type at every use site.
			continue
		}
		typeName := pascalCase(name)
		files = append(files, File{
			Name: typeName + ".java",
			Data: []byte(javaModel(doc, pkg, typeName, s)),
		})
	}

	files = append(files, File{Name: "Client.java", Data: []byte(javaClient(doc, pkg, opts))})
	return files, nil
}

// javaModel renders one record: typed components, a static fromJson factory
// that decodes a wire Map, and a toJson that rebuilds the wire Map with the
// original key names.
func javaModel(doc *core.Document, pkg, typeName string, s *core.Schema) string {
	var b strings.Builder
	fmt.Fprintf(&b, "package %s;\n\n", pkg)
	b.WriteString("import java.util.*;\n\n")
	b.WriteString("// Code generated by specter. Edit freely — it is yours now.\n")

	fields := resolvedFields(doc, s)

	// Record header: component list.
	var comps []string
	for _, f := range fields {
		comps = append(comps, fmt.Sprintf("%s %s", javaType(doc, f.Schema), javaFieldName(f.Name)))
	}
	fmt.Fprintf(&b, "public record %s(%s) {\n", typeName, strings.Join(comps, ", "))

	// fromJson: null-safe cast of the payload, then component-by-component decode
	// keyed by the original wire names.
	fmt.Fprintf(&b, "    public static %s fromJson(Object o) {\n", typeName)
	b.WriteString("        if (o == null) return null;\n")
	if len(fields) == 0 {
		fmt.Fprintf(&b, "        return new %s();\n", typeName)
	} else {
		b.WriteString("        Map<String, Object> m = Json.asMap(o);\n")
		fmt.Fprintf(&b, "        return new %s(\n", typeName)
		for i, f := range fields {
			expr := fmt.Sprintf("m.get(%q)", f.Name)
			comma := ","
			if i == len(fields)-1 {
				comma = ""
			}
			fmt.Fprintf(&b, "            %s%s\n", javaDecode(doc, f.Schema, expr, 0), comma)
		}
		b.WriteString("        );\n")
	}
	b.WriteString("    }\n\n")

	// toJson: rebuild the wire Map, restoring original key names and encoding
	// nested records/lists back to plain Map/List trees.
	b.WriteString("    public Object toJson() {\n")
	b.WriteString("        Map<String, Object> m = new LinkedHashMap<>();\n")
	for _, f := range fields {
		acc := javaFieldName(f.Name) + "()"
		fmt.Fprintf(&b, "        m.put(%q, %s);\n", f.Name, javaEncode(doc, f.Schema, acc, 0))
	}
	b.WriteString("        return m;\n")
	b.WriteString("    }\n")

	b.WriteString("}\n")
	return b.String()
}

// javaClient renders the Client: constructors, a single request helper on
// java.net.http, and one typed method per operation.
func javaClient(doc *core.Document, pkg string, opts Options) string {
	var b strings.Builder
	fmt.Fprintf(&b, "package %s;\n\n", pkg)
	b.WriteString("import java.net.URI;\n")
	b.WriteString("import java.net.URLEncoder;\n")
	b.WriteString("import java.net.http.HttpClient;\n")
	b.WriteString("import java.net.http.HttpRequest;\n")
	b.WriteString("import java.net.http.HttpResponse;\n")
	b.WriteString("import java.nio.charset.StandardCharsets;\n")
	b.WriteString("import java.util.*;\n\n")
	b.WriteString("// Code generated by specter. Edit freely — it is yours now.\n")

	b.WriteString("public final class Client {\n")
	fmt.Fprintf(&b, "    public static final String DEFAULT_BASE_URL = %s;\n\n", javaString(opts.BaseURL))
	b.WriteString("    private final String baseUrl;\n")
	b.WriteString("    private final String token;\n")
	b.WriteString("    private final HttpClient http = HttpClient.newHttpClient();\n\n")

	b.WriteString("    public Client() { this(DEFAULT_BASE_URL, null); }\n")
	b.WriteString("    public Client(String baseUrl) { this(baseUrl, null); }\n")
	b.WriteString("    public Client(String baseUrl, String token) {\n")
	b.WriteString("        this.baseUrl = baseUrl.replaceAll(\"/$\", \"\");\n")
	b.WriteString("        this.token = token;\n")
	b.WriteString("    }\n\n")

	// The one request helper every operation funnels through.
	b.WriteString(`    private Object request(String method, String path, Map<String, Object> query, Object body) {
        try {
            StringBuilder url = new StringBuilder(baseUrl + path);
            if (query != null) {
                boolean first = true;
                for (Map.Entry<String, Object> e : query.entrySet()) {
                    if (e.getValue() == null) continue;
                    url.append(first ? "?" : "&");
                    first = false;
                    url.append(URLEncoder.encode(e.getKey(), StandardCharsets.UTF_8));
                    url.append("=");
                    url.append(URLEncoder.encode(String.valueOf(e.getValue()), StandardCharsets.UTF_8));
                }
            }
            HttpRequest.Builder rb = HttpRequest.newBuilder(URI.create(url.toString()));
            if (token != null) rb.header("Authorization", "Bearer " + token);
            if (body != null) {
                rb.header("Content-Type", "application/json");
                rb.method(method, HttpRequest.BodyPublishers.ofString(Json.write(body)));
            } else {
                rb.method(method, HttpRequest.BodyPublishers.noBody());
            }
            HttpResponse<String> res = http.send(rb.build(), HttpResponse.BodyHandlers.ofString());
            String text = res.body();
            Object data = (text == null || text.isEmpty()) ? null : Json.parse(text);
            if (res.statusCode() < 200 || res.statusCode() > 299) {
                throw new ApiException(res.statusCode(), data);
            }
            return data;
        } catch (java.io.IOException | InterruptedException e) {
            throw new RuntimeException(e);
        }
    }
`)

	for _, op := range flatten(doc) {
		writeJavaMethod(&b, doc, op)
	}

	b.WriteString("}\n")
	return b.String()
}

func writeJavaMethod(b *strings.Builder, doc *core.Document, op operation) {
	var params []string
	for _, p := range op.PathParams {
		params = append(params, "String "+javaParamName(p))
	}
	if op.Body != nil {
		params = append(params, javaType(doc, op.Body)+" body")
	}
	if len(op.Query) > 0 {
		params = append(params, "Map<String, Object> query")
	}

	result := "void"
	if op.Result != nil {
		result = javaType(doc, op.Result)
	}

	b.WriteString("\n")
	if op.Summary != "" {
		fmt.Fprintf(b, "    /** %s */\n", op.Summary)
	}
	if op.Deprecated {
		b.WriteString("    @Deprecated\n")
	}
	fmt.Fprintf(b, "    public %s %s(%s) {\n", result, javaMethodName(op.Name), strings.Join(params, ", "))

	fmt.Fprintf(b, "        String path = %s;\n", javaString(op.Path))
	for _, p := range op.PathParams {
		fmt.Fprintf(b, "        path = path.replace(%q, String.valueOf(%s));\n", "{"+p+"}", javaParamName(p))
	}

	query := "null"
	if len(op.Query) > 0 {
		query = "query"
	}
	body := "null"
	if op.Body != nil {
		body = javaEncode(doc, op.Body, "body", 0)
	}

	if result == "void" {
		fmt.Fprintf(b, "        request(%q, path, %s, %s);\n", op.Method, query, body)
	} else {
		fmt.Fprintf(b, "        Object data = request(%q, path, %s, %s);\n", op.Method, query, body)
		fmt.Fprintf(b, "        return %s;\n", javaDecode(doc, op.Result, "data", 0))
	}
	b.WriteString("    }\n")
}

// javaType maps a schema to a Java type. Refs resolve through aliases and
// non-object schemas to a concrete type; structs become their record name.
func javaType(doc *core.Document, s *core.Schema) string {
	if s == nil {
		return "Object"
	}
	if s.Ref != "" {
		target := doc.Components.Schemas[refName(s.Ref)]
		if target == nil {
			return "Object"
		}
		if isStruct(target) && aliasTarget(target) == nil {
			return pascalCase(refName(s.Ref))
		}
		if a := aliasTarget(target); a != nil {
			return javaType(doc, a)
		}
		return javaType(doc, target)
	}
	switch s.Type {
	case "string":
		return "String"
	case "integer":
		return "long"
	case "number":
		return "double"
	case "boolean":
		return "boolean"
	case "array":
		return "List<" + javaBox(javaType(doc, s.Items)) + ">"
	case "object":
		return "Map<String, Object>"
	}
	return "Object"
}

// javaBox turns a primitive type name into its wrapper for use in generics.
func javaBox(t string) string {
	switch t {
	case "long":
		return "Long"
	case "double":
		return "Double"
	case "boolean":
		return "Boolean"
	}
	return t
}

// javaDecode builds the expression turning a wire value (expr) into the typed
// field: a referenced record via fromJson, an array element-wise, a primitive
// through a Json coercion helper. depth keeps nested-lambda parameters unique.
func javaDecode(doc *core.Document, s *core.Schema, expr string, depth int) string {
	if s == nil {
		return expr
	}
	if s.Ref != "" {
		target := doc.Components.Schemas[refName(s.Ref)]
		if target != nil && isStruct(target) && aliasTarget(target) == nil {
			return fmt.Sprintf("%s.fromJson(%s)", pascalCase(refName(s.Ref)), expr)
		}
		if target != nil {
			if a := aliasTarget(target); a != nil {
				return javaDecode(doc, a, expr, depth)
			}
			return javaDecode(doc, target, expr, depth)
		}
		return expr
	}
	switch s.Type {
	case "string":
		return fmt.Sprintf("Json.asString(%s)", expr)
	case "integer":
		return fmt.Sprintf("Json.asLong(%s)", expr)
	case "number":
		return fmt.Sprintf("Json.asDouble(%s)", expr)
	case "boolean":
		return fmt.Sprintf("Json.asBool(%s)", expr)
	case "array":
		v := fmt.Sprintf("x%d", depth)
		inner := javaDecode(doc, s.Items, v, depth+1)
		return fmt.Sprintf("Json.mapList(Json.asList(%s), %s -> %s)", expr, v, inner)
	case "object":
		return fmt.Sprintf("Json.asMap(%s)", expr)
	}
	return expr
}

// javaEncode builds the expression turning a typed value (expr) back into a
// plain Map/List/primitive tree for the wire: records via toJson, arrays
// element-wise, primitives unchanged.
func javaEncode(doc *core.Document, s *core.Schema, expr string, depth int) string {
	if s == nil {
		return expr
	}
	if s.Ref != "" {
		target := doc.Components.Schemas[refName(s.Ref)]
		if target != nil && isStruct(target) && aliasTarget(target) == nil {
			return fmt.Sprintf("(%s == null ? null : %s.toJson())", expr, expr)
		}
		if target != nil {
			if a := aliasTarget(target); a != nil {
				return javaEncode(doc, a, expr, depth)
			}
			return javaEncode(doc, target, expr, depth)
		}
		return expr
	}
	if s.Type == "array" && s.Items != nil {
		v := fmt.Sprintf("x%d", depth)
		inner := javaEncode(doc, s.Items, v, depth+1)
		if inner == v {
			return expr // primitive elements are already wire-ready
		}
		return fmt.Sprintf("Json.mapList(%s, %s -> %s)", expr, v, inner)
	}
	return expr
}

// javaString renders a Go string as a Java double-quoted literal.
func javaString(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			b.WriteString("\\\"")
		case '\\':
			b.WriteString("\\\\")
		case '\n':
			b.WriteString("\\n")
		case '\r':
			b.WriteString("\\r")
		case '\t':
			b.WriteString("\\t")
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}

func javaFieldName(name string) string  { return javaIdent(camelCase(name)) }
func javaMethodName(name string) string { return javaIdent(camelCase(name)) }

func javaParamName(name string) string {
	n := javaIdent(camelCase(name))
	switch n {
	case "query", "body", "path", "data", "url", "method":
		return n + "Param"
	}
	return n
}

func javaIdent(n string) string {
	if n == "" {
		return "field_"
	}
	if javaReserved[n] {
		return n + "_"
	}
	if n[0] >= '0' && n[0] <= '9' {
		return "f_" + n
	}
	return n
}

var javaReserved = map[string]bool{
	"abstract": true, "assert": true, "boolean": true, "break": true, "byte": true,
	"case": true, "catch": true, "char": true, "class": true, "const": true,
	"continue": true, "default": true, "do": true, "double": true, "else": true,
	"enum": true, "extends": true, "final": true, "finally": true, "float": true,
	"for": true, "goto": true, "if": true, "implements": true, "import": true,
	"instanceof": true, "int": true, "interface": true, "long": true, "native": true,
	"new": true, "package": true, "private": true, "protected": true, "public": true,
	"return": true, "short": true, "static": true, "strictfp": true, "super": true,
	"switch": true, "synchronized": true, "this": true, "throw": true, "throws": true,
	"transient": true, "try": true, "void": true, "volatile": true, "while": true,
	"true": true, "false": true, "null": true, "var": true, "record": true,
	"yield": true, "sealed": true, "permits": true,
}

// javaApiException renders the thrown-on-non-2xx exception, carrying the
// decoded body for inspection.
func javaApiException(pkg string) string {
	return fmt.Sprintf(`package %s;

// Code generated by specter. Edit freely — it is yours now.
public class ApiException extends RuntimeException {
    public final int status;
    public final Object body;

    public ApiException(int status, Object body) {
        super("request failed: " + status);
        this.status = status;
        this.body = body;
    }
}
`, pkg)
}

// javaJsonRuntime renders Json.java: a hand-written, dependency-free JSON
// library. parse(String) yields Map<String,Object>/List<Object>/String/Double/
// Boolean/null; write(Object) serializes those types back to text. The asX and
// mapList helpers back the generated fromJson/toJson.
func javaJsonRuntime(pkg string) string {
	return fmt.Sprintf("package %s;\n\n%s", pkg, javaJsonBody)
}

const javaJsonBody = `import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Function;

// Code generated by specter. Edit freely — it is yours now.

/** A tiny dependency-free JSON runtime: parse text to Object trees and back. */
public final class Json {
    private Json() {}

    // ---- coercion helpers used by generated fromJson/toJson ----
    public static String asString(Object o) { return o == null ? null : o.toString(); }

    public static long asLong(Object o) { return o == null ? 0L : ((Number) o).longValue(); }

    public static double asDouble(Object o) { return o == null ? 0.0 : ((Number) o).doubleValue(); }

    public static boolean asBool(Object o) { return o != null && (Boolean) o; }

    @SuppressWarnings("unchecked")
    public static Map<String, Object> asMap(Object o) { return (Map<String, Object>) o; }

    @SuppressWarnings("unchecked")
    public static List<Object> asList(Object o) { return (List<Object>) o; }

    public static <A, B> List<B> mapList(List<A> in, Function<A, B> f) {
        List<B> out = new ArrayList<>();
        if (in != null) {
            for (A x : in) out.add(f.apply(x));
        }
        return out;
    }

    // ---- parser (recursive descent) ----
    public static Object parse(String s) {
        Parser p = new Parser(s);
        p.ws();
        Object v = p.value();
        p.ws();
        if (!p.end()) throw p.err("trailing data");
        return v;
    }

    private static final class Parser {
        final String s;
        int pos;

        Parser(String s) { this.s = s; }

        boolean end() { return pos >= s.length(); }

        char peek() { return s.charAt(pos); }

        char next() {
            if (end()) throw err("unexpected end of input");
            return s.charAt(pos++);
        }

        void ws() {
            while (!end()) {
                char c = peek();
                if (c == ' ' || c == '\t' || c == '\n' || c == '\r') pos++;
                else break;
            }
        }

        Object value() {
            if (end()) throw err("unexpected end of input");
            char c = peek();
            switch (c) {
                case '{': return object();
                case '[': return array();
                case '"': return string();
                case 't':
                case 'f': return bool();
                case 'n': return nul();
                default: return number();
            }
        }

        Map<String, Object> object() {
            expect('{');
            ws();
            Map<String, Object> m = new LinkedHashMap<>();
            if (peek() == '}') { pos++; return m; }
            while (true) {
                ws();
                String k = string();
                ws();
                expect(':');
                ws();
                m.put(k, value());
                ws();
                char c = next();
                if (c == '}') return m;
                if (c != ',') throw err("expected ',' or '}'");
            }
        }

        List<Object> array() {
            expect('[');
            ws();
            List<Object> a = new ArrayList<>();
            if (peek() == ']') { pos++; return a; }
            while (true) {
                ws();
                a.add(value());
                ws();
                char c = next();
                if (c == ']') return a;
                if (c != ',') throw err("expected ',' or ']'");
            }
        }

        String string() {
            expect('"');
            StringBuilder sb = new StringBuilder();
            while (true) {
                char c = next();
                if (c == '"') return sb.toString();
                if (c == '\\') {
                    char e = next();
                    switch (e) {
                        case '"': sb.append('"'); break;
                        case '\\': sb.append('\\'); break;
                        case '/': sb.append('/'); break;
                        case 'b': sb.append('\b'); break;
                        case 'f': sb.append('\f'); break;
                        case 'n': sb.append('\n'); break;
                        case 'r': sb.append('\r'); break;
                        case 't': sb.append('\t'); break;
                        case 'u':
                            String hex = s.substring(pos, pos + 4);
                            pos += 4;
                            sb.append((char) Integer.parseInt(hex, 16));
                            break;
                        default: throw err("invalid escape '\\" + e + "'");
                    }
                } else {
                    sb.append(c);
                }
            }
        }

        Object number() {
            int start = pos;
            while (!end()) {
                char c = peek();
                if ((c >= '0' && c <= '9') || c == '-' || c == '+' || c == '.' || c == 'e' || c == 'E') pos++;
                else break;
            }
            String num = s.substring(start, pos);
            if (num.isEmpty()) throw err("invalid number");
            return Double.parseDouble(num);
        }

        Boolean bool() {
            if (s.startsWith("true", pos)) { pos += 4; return Boolean.TRUE; }
            if (s.startsWith("false", pos)) { pos += 5; return Boolean.FALSE; }
            throw err("invalid literal");
        }

        Object nul() {
            if (s.startsWith("null", pos)) { pos += 4; return null; }
            throw err("invalid literal");
        }

        void expect(char c) {
            if (next() != c) throw err("expected '" + c + "'");
        }

        IllegalArgumentException err(String m) {
            return new IllegalArgumentException("json: " + m + " at position " + pos);
        }
    }

    // ---- serializer ----
    public static String write(Object o) {
        StringBuilder sb = new StringBuilder();
        writeValue(sb, o);
        return sb.toString();
    }

    private static void writeValue(StringBuilder sb, Object o) {
        if (o == null) { sb.append("null"); return; }
        if (o instanceof String str) { writeString(sb, str); return; }
        if (o instanceof Boolean b) { sb.append(b.booleanValue()); return; }
        if (o instanceof Double d) { sb.append(fmtNum(d)); return; }
        if (o instanceof Float f) { sb.append(fmtNum(f.doubleValue())); return; }
        if (o instanceof Number n) { sb.append(n.toString()); return; }
        if (o instanceof Map<?, ?> m) { writeObject(sb, m); return; }
        if (o instanceof List<?> l) { writeArray(sb, l); return; }
        writeString(sb, o.toString());
    }

    private static String fmtNum(double d) {
        if (d == Math.rint(d) && !Double.isInfinite(d)) return Long.toString((long) d);
        return Double.toString(d);
    }

    private static void writeObject(StringBuilder sb, Map<?, ?> m) {
        sb.append('{');
        boolean first = true;
        for (Map.Entry<?, ?> e : m.entrySet()) {
            if (!first) sb.append(',');
            first = false;
            writeString(sb, String.valueOf(e.getKey()));
            sb.append(':');
            writeValue(sb, e.getValue());
        }
        sb.append('}');
    }

    private static void writeArray(StringBuilder sb, List<?> l) {
        sb.append('[');
        boolean first = true;
        for (Object x : l) {
            if (!first) sb.append(',');
            first = false;
            writeValue(sb, x);
        }
        sb.append(']');
    }

    private static void writeString(StringBuilder sb, String s) {
        sb.append('"');
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            switch (c) {
                case '"': sb.append("\\\""); break;
                case '\\': sb.append("\\\\"); break;
                case '\n': sb.append("\\n"); break;
                case '\r': sb.append("\\r"); break;
                case '\t': sb.append("\\t"); break;
                case '\b': sb.append("\\b"); break;
                case '\f': sb.append("\\f"); break;
                default:
                    if (c < 0x20) sb.append(String.format("\\u%04x", (int) c));
                    else sb.append(c);
            }
        }
        sb.append('"');
    }
}
`
