package sdk

import (
	"fmt"
	"strings"

	"github.com/bakhod1r/spector/internal/core"
)

// generateJS renders one self-contained client.js (ESM) on top of fetch, with
// JSDoc @typedef blocks giving an editor the same types the TypeScript client
// carries. JavaScript is dynamically typed, so a response is returned as the
// parsed JSON object directly — the typedefs describe its shape without a
// runtime cost.
func generateJS(doc *core.Document, opts Options) ([]File, error) {
	var b strings.Builder

	b.WriteString("// Code generated by specter. Edit freely — it is yours now.\n\n")

	for _, name := range sortedSchemaNames(doc) {
		writeJSTypedef(&b, doc, name, doc.Components.Schemas[name])
	}

	b.WriteString(`export class ApiError extends Error {
  constructor(status, body) {
    super(` + "`request failed: ${status}`" + `);
    this.name = "ApiError";
    this.status = status;
    this.body = body;
  }
}

`)

	fmt.Fprintf(&b, `export class Client {
  /**
   * @param {{ baseUrl?: string, token?: string, fetch?: typeof fetch }} [opts]
   */
  constructor(opts = {}) {
    this.baseUrl = (opts.baseUrl ?? %q).replace(/\/$/, "");
    this.token = opts.token;
    this.fetchImpl = opts.fetch ?? fetch;
  }

  async #request(method, path, query, body) {
    const url = new URL(this.baseUrl + path);
    for (const [k, v] of Object.entries(query ?? {})) {
      if (v !== undefined && v !== null) url.searchParams.set(k, String(v));
    }
    const headers = {};
    if (body !== undefined) headers["Content-Type"] = "application/json";
    if (this.token) headers["Authorization"] = `+"`Bearer ${this.token}`"+`;
    const res = await this.fetchImpl(url, {
      method,
      headers,
      body: body === undefined ? undefined : JSON.stringify(body),
    });
    const text = await res.text();
    const data = text ? JSON.parse(text) : undefined;
    if (!res.ok) throw new ApiError(res.status, data);
    return data;
  }
`, opts.BaseURL)

	for _, op := range flatten(doc) {
		writeJSMethod(&b, op)
	}

	b.WriteString("}\n")
	return []File{{Name: "client.js", Data: []byte(b.String())}}, nil
}

func writeJSTypedef(b *strings.Builder, doc *core.Document, name string, s *core.Schema) {
	if s == nil {
		return
	}
	typeName := pascalCase(name)
	if a := aliasTarget(s); a != nil {
		fmt.Fprintf(b, "/** @typedef {%s} %s */\n\n", jsType(a), typeName)
		return
	}
	if !isStruct(s) {
		fmt.Fprintf(b, "/** @typedef {%s} %s */\n\n", jsType(s), typeName)
		return
	}
	fmt.Fprintf(b, "/**\n * @typedef {Object} %s\n", typeName)
	for _, f := range resolvedFields(doc, s) {
		opt := ""
		if !f.Required {
			opt = "["
		}
		close := ""
		if !f.Required {
			close = "]"
		}
		fmt.Fprintf(b, " * @property {%s} %s%s%s\n", jsType(f.Schema), opt, jsPropName(f.Name), close)
	}
	b.WriteString(" */\n\n")
}

func writeJSMethod(b *strings.Builder, op operation) {
	var params []string
	for _, p := range op.PathParams {
		params = append(params, jsParamName(p))
	}
	if op.Body != nil {
		params = append(params, "body")
	}
	if len(op.Query) > 0 {
		params = append(params, "query")
	}

	ret := "void"
	if op.Result != nil {
		ret = jsType(op.Result)
	}

	b.WriteString("\n  /**\n")
	if op.Summary != "" {
		fmt.Fprintf(b, "   * %s\n", op.Summary)
	}
	if op.Deprecated {
		b.WriteString("   * @deprecated\n")
	}
	fmt.Fprintf(b, "   * @returns {Promise<%s>}\n   */\n", ret)

	fmt.Fprintf(b, "  async %s(%s) {\n", camelCase(op.Name), strings.Join(params, ", "))

	path := op.Path
	for _, p := range op.PathParams {
		path = strings.ReplaceAll(path, "{"+p+"}", "${"+jsParamName(p)+"}")
	}
	query := "undefined"
	if len(op.Query) > 0 {
		query = "query"
	}
	body := "undefined"
	if op.Body != nil {
		body = "body"
	}
	fmt.Fprintf(b, "    return this.#request(%q, `%s`, %s, %s);\n", op.Method, path, query, body)
	b.WriteString("  }\n")
}

// jsType maps a schema to a JSDoc type expression.
func jsType(s *core.Schema) string {
	if s == nil {
		return "*"
	}
	if s.Ref != "" {
		return pascalCase(refName(s.Ref))
	}
	switch s.Type {
	case "string":
		return "string"
	case "integer", "number":
		return "number"
	case "boolean":
		return "boolean"
	case "array":
		return "Array<" + jsType(s.Items) + ">"
	case "object":
		if s.AdditionalProperties != nil {
			return "Object<string, " + jsType(s.AdditionalProperties) + ">"
		}
		return "Object<string, *>"
	}
	return "*"
}

func jsPropName(name string) string {
	// A JSDoc @property name is a bare identifier; original wire names that are
	// not legal identifiers are quoted the same way an object literal would.
	if isJSIdent(name) {
		return name
	}
	return fmt.Sprintf("%q", name)
}

func jsParamName(name string) string {
	n := camelCase(name)
	if n == "" || !isJSIdent(n) {
		return "param"
	}
	return n
}

func isJSIdent(name string) bool {
	if name == "" {
		return false
	}
	for i, r := range name {
		ok := r == '_' || r == '$' ||
			(r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') ||
			(i > 0 && r >= '0' && r <= '9')
		if !ok {
			return false
		}
	}
	return true
}
