package sdk

import (
	"fmt"
	"strings"

	"github.com/bakhod1r/spector/internal/core"
)

// generateKotlin renders one self-contained Client.kt: a @Serializable data
// class per schema and a Client with a typed method per operation, on
// java.net.http.HttpClient and kotlinx.serialization. Properties are camelCase
// with an explicit @SerialName so the wire JSON keeps its original key names,
// and every property carries a default so a partial payload still deserializes.
func generateKotlin(doc *core.Document, opts Options) ([]File, error) {
	var b strings.Builder

	pkg := opts.Package
	if pkg == "" {
		pkg = "apiclient"
	}

	b.WriteString("// Code generated by specter. Edit freely — it is yours now.\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	b.WriteString("import kotlinx.serialization.SerialName\n")
	b.WriteString("import kotlinx.serialization.Serializable\n")
	b.WriteString("import kotlinx.serialization.encodeToString\n")
	b.WriteString("import kotlinx.serialization.json.Json\n")
	b.WriteString("import kotlinx.serialization.json.JsonElement\n")
	b.WriteString("import kotlinx.serialization.serializer\n")
	b.WriteString("import java.net.URI\n")
	b.WriteString("import java.net.URLEncoder\n")
	b.WriteString("import java.net.http.HttpClient\n")
	b.WriteString("import java.net.http.HttpRequest\n")
	b.WriteString("import java.net.http.HttpResponse\n")
	b.WriteString("import java.nio.charset.StandardCharsets\n\n")

	for _, name := range sortedSchemaNames(doc) {
		writeKotlinType(&b, doc, name, doc.Components.Schemas[name])
	}

	b.WriteString(`/** A non-2xx response. The raw body, if any, is kept for inspection. */
class ApiException(val status: Int, val body: String?) : RuntimeException("request failed: $status")

`)

	fmt.Fprintf(&b, `/** Typed client for the API. Pass a baseUrl, and a token when the API
 * authenticates with a bearer scheme. */
class Client(private val baseUrl: String = %q, private val token: String? = null) {
    private val json = Json { ignoreUnknownKeys = true; encodeDefaults = true }
    private val http = HttpClient.newHttpClient()

    private inline fun <reified T> request(
        method: String,
        path: String,
        query: Map<String, Any?>? = null,
        body: Any? = null,
    ): T {
        var url = baseUrl.trimEnd('/') + path
        if (query != null) {
            val parts = query.entries
                .filter { it.value != null }
                .map {
                    URLEncoder.encode(it.key, StandardCharsets.UTF_8) + "=" +
                        URLEncoder.encode(it.value.toString(), StandardCharsets.UTF_8)
                }
            if (parts.isNotEmpty()) url += "?" + parts.joinToString("&")
        }
        val builder = HttpRequest.newBuilder(URI.create(url))
        token?.let { builder.header("Authorization", "Bearer $it") }
        if (body != null) {
            builder.header("Content-Type", "application/json")
            builder.method(method, HttpRequest.BodyPublishers.ofString(json.encodeToString(serializer(body::class.java), body)))
        } else {
            builder.method(method, HttpRequest.BodyPublishers.noBody())
        }
        val resp = http.send(builder.build(), HttpResponse.BodyHandlers.ofString())
        if (resp.statusCode() < 200 || resp.statusCode() > 299) {
            throw ApiException(resp.statusCode(), resp.body())
        }
        val text = resp.body()
        if (text.isNullOrEmpty()) return Unit as T
        return json.decodeFromString(serializer<T>(), text)
    }

`, opts.BaseURL)

	for _, op := range flatten(doc) {
		writeKotlinMethod(&b, op)
	}

	b.WriteString("}\n")
	return []File{{Name: "Client.kt", Data: []byte(b.String())}}, nil
}

func writeKotlinType(b *strings.Builder, doc *core.Document, name string, s *core.Schema) {
	if s == nil {
		return
	}
	typeName := pascalCase(name)
	// An allOf-of-one-ref (or any non-struct schema) is a plain alias for the
	// type it wraps.
	if a := aliasTarget(s); a != nil {
		fmt.Fprintf(b, "typealias %s = %s\n\n", typeName, kotlinType(a))
		return
	}
	if !isStruct(s) {
		fmt.Fprintf(b, "typealias %s = %s\n\n", typeName, kotlinType(s))
		return
	}

	fields := resolvedFields(doc, s)
	if len(fields) == 0 {
		fmt.Fprintf(b, "@Serializable\nclass %s\n\n", typeName)
		return
	}
	fmt.Fprintf(b, "@Serializable\ndata class %s(\n", typeName)
	for _, f := range fields {
		fmt.Fprintf(b, "    @SerialName(%q) val %s: %s = %s,\n",
			f.Name, kotlinFieldName(f.Name), kotlinType(f.Schema), kotlinDefault(f.Schema))
	}
	b.WriteString(")\n\n")
}

func writeKotlinMethod(b *strings.Builder, op operation) {
	var params []string
	for _, p := range op.PathParams {
		params = append(params, fmt.Sprintf("%s: String", kotlinParamName(p)))
	}
	if op.Body != nil {
		params = append(params, "body: "+kotlinType(op.Body))
	}
	if len(op.Query) > 0 {
		params = append(params, "query: Map<String, Any?>? = null")
	}

	result := "Unit"
	if op.Result != nil {
		result = kotlinType(op.Result)
	}

	if op.Summary != "" || op.Deprecated {
		b.WriteString("    /**")
		if op.Summary != "" {
			fmt.Fprintf(b, " %s", op.Summary)
		}
		b.WriteString(" */\n")
	}
	if op.Deprecated {
		b.WriteString("    @Deprecated(\"the API marks this operation deprecated\")\n")
	}
	fmt.Fprintf(b, "    fun %s(%s): %s {\n", kotlinMethodName(op.Name), strings.Join(params, ", "), result)

	path := op.Path
	for _, p := range op.PathParams {
		path = strings.ReplaceAll(path, "{"+p+"}", "${"+kotlinParamName(p)+"}")
	}
	// Kotlin string templates interpolate $, so a literal path with no params is
	// still fine as a normal quoted string.
	var call []string
	call = append(call, fmt.Sprintf("%q", op.Method))
	call = append(call, fmt.Sprintf("%q", path))
	if len(op.Query) > 0 {
		call = append(call, "query = query")
	}
	if op.Body != nil {
		call = append(call, "body = body")
	}
	fmt.Fprintf(b, "        return request(%s)\n", strings.Join(call, ", "))
	b.WriteString("    }\n\n")
}

// kotlinType maps a JSON Schema fragment to a Kotlin type expression.
func kotlinType(s *core.Schema) string {
	if s == nil {
		return "JsonElement"
	}
	if s.Ref != "" {
		return pascalCase(refName(s.Ref))
	}
	switch s.Type {
	case "string":
		return "String"
	case "integer":
		return "Int"
	case "number":
		return "Double"
	case "boolean":
		return "Boolean"
	case "array":
		return "List<" + kotlinType(s.Items) + ">"
	case "object":
		if s.AdditionalProperties != nil {
			return "Map<String, " + kotlinType(s.AdditionalProperties) + ">"
		}
		return "JsonElement"
	}
	return "JsonElement"
}

// kotlinDefault gives every property a default so a partial payload still
// constructs, and encodeDefaults keeps them on the wire.
func kotlinDefault(s *core.Schema) string {
	if s == nil {
		return "kotlinx.serialization.json.JsonNull"
	}
	if s.Ref != "" {
		return pascalCase(refName(s.Ref)) + "()"
	}
	switch s.Type {
	case "string":
		return "\"\""
	case "integer":
		return "0"
	case "number":
		return "0.0"
	case "boolean":
		return "false"
	case "array":
		return "emptyList()"
	case "object":
		if s.AdditionalProperties != nil {
			return "emptyMap()"
		}
		return "kotlinx.serialization.json.JsonNull"
	}
	return "kotlinx.serialization.json.JsonNull"
}

func kotlinFieldName(name string) string  { return kotlinIdent(camelCase(name)) }
func kotlinParamName(name string) string  { return kotlinIdent(camelCase(name)) }
func kotlinMethodName(name string) string { return kotlinIdent(camelCase(name)) }

// kotlinIdent keeps an identifier legal, escaping the hard keywords that cannot
// appear bare with backticks.
func kotlinIdent(n string) string {
	if n == "" {
		return "field_"
	}
	switch n {
	case "as", "break", "class", "continue", "do", "else", "false", "for", "fun",
		"if", "in", "interface", "is", "null", "object", "package", "return",
		"super", "this", "throw", "true", "try", "typealias", "typeof", "val",
		"var", "when", "while":
		return "`" + n + "`"
	}
	if n[0] >= '0' && n[0] <= '9' {
		return "f_" + n
	}
	return n
}
