package sdk

import (
	"fmt"
	"strings"

	"github.com/bakhod1r/spector/internal/core"
)

// generatePHP renders one self-contained client.php: a class per schema and a
// Client with a typed method per operation, on ext-curl alone. Properties keep
// their original wire key names with fromArray/toArray so the JSON shape is
// preserved, while class names are PascalCase and method names camelCase.
func generatePHP(doc *core.Document, opts Options) ([]File, error) {
	var b strings.Builder

	b.WriteString("<?php\n\n")
	b.WriteString("// Code generated by spector. Edit freely — it is yours now.\n")
	b.WriteString("// Requires PHP 8.1+ with ext-curl and ext-json.\n\n")
	b.WriteString("declare(strict_types=1);\n\n")

	b.WriteString(`// _enc encodes a value for the wire: models become their toArray, arrays map.
function _enc(mixed $v): mixed
{
    if (is_object($v) && method_exists($v, 'toArray')) {
        return $v->toArray();
    }
    if (is_array($v)) {
        return array_map('_enc', $v);
    }
    return $v;
}

// ApiError is a non-2xx response. The decoded body, if any, is kept for inspection.
class ApiError extends \Exception
{
    public int $status;
    public mixed $body;

    public function __construct(int $status, mixed $body)
    {
        parent::__construct("request failed: {$status}");
        $this->status = $status;
        $this->body = $body;
    }
}

`)

	for _, name := range sortedSchemaNames(doc) {
		writePHPClass(&b, doc, name, doc.Components.Schemas[name])
	}

	fmt.Fprintf(&b, `// Client is a typed client for the API. Pass a base URL, and a token when the
// API authenticates with a bearer scheme.
class Client
{
    private string $baseUrl;
    private ?string $token;

    public function __construct(string $baseUrl = %s, ?string $token = null)
    {
        $this->baseUrl = rtrim($baseUrl, '/');
        $this->token = $token;
    }

    private function request(string $method, string $path, ?array $query = null, mixed $body = null): mixed
    {
        $url = $this->baseUrl . $path;
        if ($query !== null) {
            $clean = array_filter($query, fn ($v) => $v !== null);
            if (count($clean) > 0) {
                $url .= '?' . http_build_query($clean);
            }
        }
        $headers = [];
        $ch = curl_init($url);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, $method);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        if ($body !== null) {
            $headers[] = 'Content-Type: application/json';
            curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode(_enc($body)));
        }
        if ($this->token !== null) {
            $headers[] = 'Authorization: Bearer ' . $this->token;
        }
        if (count($headers) > 0) {
            curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        }
        $raw = curl_exec($ch);
        if ($raw === false) {
            $err = curl_error($ch);
            curl_close($ch);
            throw new ApiError(0, $err);
        }
        $status = curl_getinfo($ch, CURLINFO_RESPONSE_CODE);
        curl_close($ch);
        $data = ($raw === '') ? null : json_decode($raw, true);
        if ($status < 200 || $status > 299) {
            throw new ApiError($status, $data);
        }
        return $data;
    }

`, phpString(opts.BaseURL))

	for _, op := range flatten(doc) {
		writePHPMethod(&b, doc, op)
	}

	b.WriteString("}\n")
	return []File{{Name: "client.php", Data: []byte(b.String())}}, nil
}

func writePHPClass(b *strings.Builder, doc *core.Document, name string, s *core.Schema) {
	if s == nil {
		return
	}
	typeName := pascalCase(name)
	// PHP has no type-alias construct, so an alias or non-object schema gets a
	// short comment recording the intent; callers use the plain value.
	if a := aliasTarget(s); a != nil {
		fmt.Fprintf(b, "// %s is %s.\n\n", typeName, phpDoc(a))
		return
	}
	if !isStruct(s) {
		fmt.Fprintf(b, "// %s is %s.\n\n", typeName, phpDoc(s))
		return
	}

	fields := resolvedFields(doc, s)
	fmt.Fprintf(b, "class %s\n{\n", typeName)
	for _, f := range fields {
		fmt.Fprintf(b, "    public %s $%s;\n", phpType(f.Schema, f.Required), phpFieldName(f.Name))
	}
	if len(fields) > 0 {
		b.WriteString("\n")
	}

	// fromArray decodes wire JSON (original key names) into the object.
	fmt.Fprintf(b, "    public static function fromArray(array $d): self\n    {\n")
	fmt.Fprintf(b, "        $o = new self();\n")
	for _, f := range fields {
		expr := fmt.Sprintf("$d[%s] ?? null", phpString(f.Name))
		fmt.Fprintf(b, "        $o->%s = %s;\n", phpFieldName(f.Name), phpDecode(doc, f.Schema, expr))
	}
	b.WriteString("        return $o;\n    }\n\n")

	// toArray re-encodes to the wire shape, restoring the original key names.
	fmt.Fprintf(b, "    public function toArray(): array\n    {\n        return [\n")
	for _, f := range fields {
		fmt.Fprintf(b, "            %s => _enc($this->%s),\n", phpString(f.Name), phpFieldName(f.Name))
	}
	b.WriteString("        ];\n    }\n}\n\n")
}

func writePHPMethod(b *strings.Builder, doc *core.Document, op operation) {
	var params []string
	for _, p := range op.PathParams {
		params = append(params, "string $"+phpParamName(p))
	}
	if op.Body != nil {
		params = append(params, "mixed $body")
	}
	if len(op.Query) > 0 {
		params = append(params, "?array $query = null")
	}

	if op.Summary != "" {
		fmt.Fprintf(b, "    // %s\n", op.Summary)
	}
	if op.Deprecated {
		fmt.Fprintf(b, "    // Deprecated: the API marks this operation deprecated.\n")
	}
	fmt.Fprintf(b, "    public function %s(%s): mixed\n    {\n", phpMethodName(op.Name), strings.Join(params, ", "))

	path := op.Path
	for _, p := range op.PathParams {
		path = strings.ReplaceAll(path, "{"+p+"}", "{$"+phpParamName(p)+"}")
	}
	fmt.Fprintf(b, "        $path = %s;\n", phpInterp(path))

	query := "null"
	if len(op.Query) > 0 {
		query = "$query"
	}
	body := "null"
	if op.Body != nil {
		body = "$body"
	}
	fmt.Fprintf(b, "        $data = $this->request(%s, $path, %s, %s);\n", phpString(op.Method), query, body)
	fmt.Fprintf(b, "        return %s;\n    }\n\n", phpDecode(doc, op.Result, "$data"))
}

// phpType maps a schema to a PHP type hint. A non-required field is nullable so
// a partial payload still constructs.
func phpType(s *core.Schema, required bool) string {
	t := phpBaseType(s)
	if !required && t != "mixed" {
		return "?" + t
	}
	return t
}

func phpBaseType(s *core.Schema) string {
	if s == nil {
		return "mixed"
	}
	if s.Ref != "" {
		return pascalCase(refName(s.Ref))
	}
	switch s.Type {
	case "string":
		return "string"
	case "integer":
		return "int"
	case "number":
		return "float"
	case "boolean":
		return "bool"
	case "array", "object":
		return "array"
	}
	return "mixed"
}

// phpDecode builds the expression that turns a wire value into the typed field:
// a referenced struct through its fromArray, an array element-wise, a primitive
// as-is.
func phpDecode(doc *core.Document, s *core.Schema, expr string) string {
	if s == nil {
		return expr
	}
	if s.Ref != "" {
		target := doc.Components.Schemas[refName(s.Ref)]
		if target != nil && isStruct(target) && aliasTarget(target) == nil {
			p := pascalCase(refName(s.Ref))
			// A closure keeps the source expression evaluated once while still
			// guarding the null case: fromArray wants an array.
			return fmt.Sprintf("(fn ($v) => $v === null ? null : %s::fromArray($v))(%s)", p, expr)
		}
		return phpDecode(doc, target, expr)
	}
	if s.Type == "array" && s.Items != nil {
		inner := phpDecode(doc, s.Items, "$x")
		if inner == "$x" {
			return fmt.Sprintf("(%s ?? [])", expr)
		}
		return fmt.Sprintf("array_map(fn ($x) => %s, %s ?? [])", inner, expr)
	}
	return expr
}

// phpDoc describes a non-class schema in a comment.
func phpDoc(s *core.Schema) string {
	if s == nil {
		return "an untyped value"
	}
	if s.Ref != "" {
		return "a " + pascalCase(refName(s.Ref))
	}
	switch s.Type {
	case "array":
		return "an array"
	case "object":
		return "an associative array"
	case "":
		return "an untyped value"
	default:
		return "a " + s.Type
	}
}

// phpString renders a Go string as a single-quoted PHP string literal.
func phpString(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `'`, `\'`)
	return "'" + r.Replace(s) + "'"
}

// phpInterp renders a path with {$var} interpolations as a double-quoted PHP
// string when it holds variables, and a single-quoted literal otherwise.
func phpInterp(path string) string {
	if strings.Contains(path, "{$") {
		r := strings.NewReplacer(`\`, `\\`, `"`, `\"`)
		return `"` + r.Replace(path) + `"`
	}
	return phpString(path)
}

func phpFieldName(name string) string  { return phpIdent(camelCase(name)) }
func phpParamName(name string) string  { return phpIdent(camelCase(name)) }
func phpMethodName(name string) string { return phpIdent(camelCase(name)) }

// phpIdent keeps identifiers legal, guarding the PHP reserved words a scanned
// field or operation name could collide with.
func phpIdent(n string) string {
	if n == "" {
		return "field_"
	}
	switch strings.ToLower(n) {
	case "list", "class", "function", "array", "echo", "print", "if", "else",
		"elseif", "while", "for", "foreach", "do", "switch", "case", "default",
		"break", "continue", "return", "new", "clone", "try", "catch", "finally",
		"throw", "public", "private", "protected", "static", "const", "var",
		"global", "namespace", "use", "trait", "interface", "extends", "implements",
		"abstract", "final", "instanceof", "insteadof", "and", "or", "xor",
		"as", "match", "fn", "yield", "empty", "isset", "unset", "exit", "die",
		"require", "include", "true", "false", "null", "enum":
		return n + "_"
	}
	if n[0] >= '0' && n[0] <= '9' {
		return "f_" + n
	}
	return n
}
