package sdk

import (
	"fmt"
	"strings"

	"github.com/bakhod1r/spector/internal/core"
)

// generatePython renders one self-contained client.py: a dataclass per schema
// and a Client with a typed method per operation, on urllib alone. Field names
// are snake_case with explicit from_dict/to_dict so the wire JSON keeps its
// original names while the Python surface stays idiomatic.
func generatePython(doc *core.Document, opts Options) ([]File, error) {
	var b strings.Builder

	b.WriteString("# Code generated by spector. Edit freely — it is yours now.\n")
	b.WriteString("from __future__ import annotations\n\n")
	b.WriteString("import json\n")
	b.WriteString("import urllib.error\n")
	b.WriteString("import urllib.parse\n")
	b.WriteString("import urllib.request\n")
	b.WriteString("from dataclasses import dataclass, field\n")
	b.WriteString("from typing import Any, Optional\n\n\n")

	b.WriteString(`def _enc(v):
    """Encode a value for the wire: dataclasses become their to_dict, lists map."""
    if hasattr(v, "to_dict"):
        return v.to_dict()
    if isinstance(v, list):
        return [_enc(x) for x in v]
    return v


class APIError(Exception):
    """A non-2xx response. The decoded body, if any, is kept for inspection."""

    def __init__(self, status: int, body: Any):
        super().__init__(f"request failed: {status}")
        self.status = status
        self.body = body


`)

	for _, name := range sortedSchemaNames(doc) {
		writePyType(&b, doc, name, doc.Components.Schemas[name])
	}

	base := opts.BaseURL
	fmt.Fprintf(&b, `class Client:
    """Typed client for the API. Pass a base_url, and a token when the API
    authenticates with a bearer scheme."""

    def __init__(self, base_url: str = %q, token: Optional[str] = None):
        self.base_url = base_url.rstrip("/")
        self.token = token

    def _request(self, method: str, path: str, query=None, body=None) -> Any:
        url = self.base_url + path
        if query:
            clean = {k: v for k, v in query.items() if v is not None}
            if clean:
                url += "?" + urllib.parse.urlencode(clean)
        data = None
        headers = {}
        if body is not None:
            data = json.dumps(_enc(body)).encode()
            headers["Content-Type"] = "application/json"
        if self.token:
            headers["Authorization"] = "Bearer " + self.token
        req = urllib.request.Request(url, data=data, headers=headers, method=method)
        try:
            with urllib.request.urlopen(req) as resp:
                raw = resp.read()
                return json.loads(raw) if raw else None
        except urllib.error.HTTPError as e:
            raw = e.read()
            try:
                parsed = json.loads(raw) if raw else None
            except ValueError:
                parsed = raw.decode(errors="replace")
            raise APIError(e.code, parsed) from None

`, base)

	for _, op := range flatten(doc) {
		writePyMethod(&b, doc, op)
	}

	return []File{{Name: "client.py", Data: []byte(b.String())}}, nil
}

func writePyType(b *strings.Builder, doc *core.Document, name string, s *core.Schema) {
	if s == nil {
		return
	}
	typeName := pascalCase(name)
	if a := aliasTarget(s); a != nil {
		fmt.Fprintf(b, "%s = %s\n\n\n", typeName, pyType(a))
		return
	}
	if !isStruct(s) {
		fmt.Fprintf(b, "%s = %s\n\n\n", typeName, pyType(s))
		return
	}

	fields := resolvedFields(doc, s)
	fmt.Fprintf(b, "@dataclass\nclass %s:\n", typeName)
	if len(fields) == 0 {
		b.WriteString("    pass\n\n\n")
		return
	}
	// Every field carries a default so declaration order never trips the
	// dataclass "non-default after default" rule, and a partial payload still
	// constructs.
	for _, f := range fields {
		fmt.Fprintf(b, "    %s: %s = %s\n", pyFieldName(f.Name), pyType(f.Schema), pyDefault(f.Schema))
	}
	b.WriteString("\n")

	// from_dict decodes wire JSON (original key names) into the dataclass.
	fmt.Fprintf(b, "    @classmethod\n    def from_dict(cls, d: Any) -> \"%s\":\n", typeName)
	b.WriteString("        d = d or {}\n")
	b.WriteString("        return cls(\n")
	for _, f := range fields {
		expr := fmt.Sprintf("d.get(%q)", f.Name)
		fmt.Fprintf(b, "            %s=%s,\n", pyFieldName(f.Name), pyDecode(doc, f.Schema, expr))
	}
	b.WriteString("        )\n\n")

	// to_dict re-encodes to the wire shape, restoring the original key names.
	b.WriteString("    def to_dict(self) -> dict:\n")
	b.WriteString("        return {\n")
	for _, f := range fields {
		fmt.Fprintf(b, "            %q: _enc(self.%s),\n", f.Name, pyFieldName(f.Name))
	}
	b.WriteString("        }\n\n\n")
}

func writePyMethod(b *strings.Builder, doc *core.Document, op operation) {
	var params []string
	params = append(params, "self")
	for _, p := range op.PathParams {
		params = append(params, pyParamName(p))
	}
	if op.Body != nil {
		params = append(params, "body")
	}
	if len(op.Query) > 0 {
		params = append(params, "query=None")
	}

	fmt.Fprintf(b, "    def %s(%s):\n", pySnakeMethod(op.Name), strings.Join(params, ", "))
	if op.Summary != "" {
		fmt.Fprintf(b, "        %q\n", op.Summary)
	}

	path := op.Path
	for _, p := range op.PathParams {
		path = strings.ReplaceAll(path, "{"+p+"}", "{"+pyParamName(p)+"}")
	}
	fmt.Fprintf(b, "        path = f%q\n", path)

	query := "None"
	if len(op.Query) > 0 {
		query = "query"
	}
	body := "None"
	if op.Body != nil {
		body = "body"
	}
	fmt.Fprintf(b, "        data = self._request(%q, path, query=%s, body=%s)\n", op.Method, query, body)
	fmt.Fprintf(b, "        return %s\n\n", pyDecode(doc, op.Result, "data"))
}

// pyType maps a schema to a Python type annotation.
func pyType(s *core.Schema) string {
	if s == nil {
		return "Any"
	}
	if s.Ref != "" {
		return pascalCase(refName(s.Ref))
	}
	switch s.Type {
	case "string":
		return "str"
	case "integer":
		return "int"
	case "number":
		return "float"
	case "boolean":
		return "bool"
	case "array":
		return "list[" + pyType(s.Items) + "]"
	case "object":
		if s.AdditionalProperties != nil {
			return "dict[str, " + pyType(s.AdditionalProperties) + "]"
		}
		return "dict[str, Any]"
	}
	return "Any"
}

// pyDefault gives a field a safe default: an empty list/dict factory for
// collections, None otherwise.
func pyDefault(s *core.Schema) string {
	if s != nil {
		switch s.Type {
		case "array":
			return "field(default_factory=list)"
		case "object":
			return "field(default_factory=dict)"
		}
	}
	return "None"
}

// pyDecode builds the expression that turns a wire value into the typed field:
// a referenced struct through its from_dict, an array element-wise, a primitive
// as-is.
func pyDecode(doc *core.Document, s *core.Schema, expr string) string {
	if s == nil {
		return expr
	}
	if s.Ref != "" {
		target := doc.Components.Schemas[refName(s.Ref)]
		if target != nil && isStruct(target) && aliasTarget(target) == nil {
			p := pascalCase(refName(s.Ref))
			return fmt.Sprintf("%s.from_dict(%s) if %s is not None else None", p, expr, expr)
		}
		return pyDecode(doc, target, expr)
	}
	if s.Type == "array" && s.Items != nil {
		inner := pyDecode(doc, s.Items, "x")
		if inner == "x" {
			return fmt.Sprintf("list(%s or [])", expr)
		}
		return fmt.Sprintf("[%s for x in (%s or [])]", inner, expr)
	}
	return expr
}

// pyFieldName / pyParamName / pySnakeMethod keep identifiers legal and
// idiomatic, guarding the handful of Python keywords a field could collide with.
func pyFieldName(name string) string { return pyIdent(snakeCase(name)) }
func pyParamName(name string) string { return pyIdent(snakeCase(name)) }
func pySnakeMethod(name string) string {
	n := snakeCase(name)
	if n == "" {
		return "call"
	}
	return n
}

func pyIdent(n string) string {
	if n == "" {
		return "field_"
	}
	switch n {
	case "class", "def", "from", "import", "return", "in", "is", "and", "or",
		"not", "None", "True", "False", "global", "lambda", "pass", "async", "await":
		return n + "_"
	}
	if n[0] >= '0' && n[0] <= '9' {
		return "f_" + n
	}
	return n
}
