package sdk

import (
	"fmt"
	"strings"

	"github.com/bakhod1r/spector/internal/core"
)

// generateRuby renders one self-contained client.rb: a class per schema and a
// Client with a typed method per operation, on net/http alone. Attributes are
// snake_case with from_h/to_h so the wire JSON keeps its original key names.
func generateRuby(doc *core.Document, opts Options) ([]File, error) {
	var b strings.Builder

	b.WriteString("# Code generated by spector. Edit freely — it is yours now.\n")
	b.WriteString("# frozen_string_literal: true\n\n")
	b.WriteString("require \"json\"\n")
	b.WriteString("require \"net/http\"\n")
	b.WriteString("require \"uri\"\n\n")

	b.WriteString(`# Encode a value for the wire: models become their to_h, arrays map.
def _enc(v)
  return v if v.nil?
  return v.map { |x| _enc(x) } if v.is_a?(Array)
  return v.to_h if v.respond_to?(:to_h) && !v.is_a?(Hash)
  v
end

# A non-2xx response. The decoded body, if any, is kept for inspection.
class ApiError < StandardError
  attr_reader :status, :body

  def initialize(status, body)
    super("request failed: #{status}")
    @status = status
    @body = body
  end
end

`)

	for _, name := range sortedSchemaNames(doc) {
		writeRubyClass(&b, doc, name, doc.Components.Schemas[name])
	}

	fmt.Fprintf(&b, `# Typed client for the API. Pass a base_url, and a token when the API
# authenticates with a bearer scheme.
class Client
  def initialize(base_url: %q, token: nil)
    @base_url = base_url.sub(%%r{/\z}, "")
    @token = token
  end

  def request(method, path, query: nil, body: nil)
    uri = URI(@base_url + path)
    if query
      clean = query.reject { |_, v| v.nil? }
      uri.query = URI.encode_www_form(clean) unless clean.empty?
    end
    req = Net::HTTP.const_get(method.capitalize).new(uri)
    req["Authorization"] = "Bearer #{@token}" if @token
    if body
      req["Content-Type"] = "application/json"
      req.body = JSON.generate(_enc(body))
    end
    res = Net::HTTP.start(uri.hostname, uri.port, use_ssl: uri.scheme == "https") do |http|
      http.request(req)
    end
    data = res.body && !res.body.empty? ? JSON.parse(res.body) : nil
    raise ApiError.new(res.code.to_i, data) unless res.is_a?(Net::HTTPSuccess)

    data
  end

`, opts.BaseURL)

	for _, op := range flatten(doc) {
		writeRubyMethod(&b, doc, op)
	}

	b.WriteString("end\n")
	return []File{{Name: "client.rb", Data: []byte(b.String())}}, nil
}

func writeRubyClass(b *strings.Builder, doc *core.Document, name string, s *core.Schema) {
	if s == nil {
		return
	}
	typeName := pascalCase(name)
	// Ruby is duck-typed: an alias or non-object schema needs no class, callers
	// use the plain value. A short comment records the intent.
	if a := aliasTarget(s); a != nil {
		fmt.Fprintf(b, "# %s is %s.\n\n", typeName, rubyDoc(a))
		return
	}
	if !isStruct(s) {
		fmt.Fprintf(b, "# %s is %s.\n\n", typeName, rubyDoc(s))
		return
	}

	fields := resolvedFields(doc, s)
	fmt.Fprintf(b, "class %s\n", typeName)
	if len(fields) > 0 {
		var accs []string
		for _, f := range fields {
			accs = append(accs, ":"+rubyFieldName(f.Name))
		}
		fmt.Fprintf(b, "  attr_accessor %s\n\n", strings.Join(accs, ", "))
	}
	b.WriteString("  def initialize(**attrs)\n")
	b.WriteString("    attrs.each { |k, v| instance_variable_set(\"@#{k}\", v) }\n")
	b.WriteString("  end\n\n")

	// from_h decodes wire JSON (original key names) into the object.
	b.WriteString("  def self.from_h(d)\n")
	b.WriteString("    d ||= {}\n")
	b.WriteString("    new(\n")
	for _, f := range fields {
		expr := fmt.Sprintf("d[%q]", f.Name)
		fmt.Fprintf(b, "      %s: %s,\n", rubyFieldName(f.Name), rubyDecode(doc, f.Schema, expr))
	}
	b.WriteString("    )\n  end\n\n")

	// to_h re-encodes to the wire shape, restoring the original key names.
	b.WriteString("  def to_h\n    {\n")
	for _, f := range fields {
		fmt.Fprintf(b, "      %q => _enc(@%s),\n", f.Name, rubyFieldName(f.Name))
	}
	b.WriteString("    }\n  end\nend\n\n")
}

func writeRubyMethod(b *strings.Builder, doc *core.Document, op operation) {
	var params []string
	for _, p := range op.PathParams {
		params = append(params, rubyParamName(p))
	}
	if op.Body != nil {
		params = append(params, "body")
	}
	if len(op.Query) > 0 {
		params = append(params, "query: nil")
	}
	sig := ""
	if len(params) > 0 {
		sig = "(" + strings.Join(params, ", ") + ")"
	}

	if op.Summary != "" {
		fmt.Fprintf(b, "  # %s\n", op.Summary)
	}
	fmt.Fprintf(b, "  def %s%s\n", rubyMethodName(op.Name), sig)

	path := op.Path
	for _, p := range op.PathParams {
		path = strings.ReplaceAll(path, "{"+p+"}", "#{"+rubyParamName(p)+"}")
	}
	var call []string
	call = append(call, fmt.Sprintf("%q", op.Method), fmt.Sprintf("%q", path))
	if len(op.Query) > 0 {
		call = append(call, "query: query")
	}
	if op.Body != nil {
		call = append(call, "body: body")
	}
	fmt.Fprintf(b, "    data = request(%s)\n", strings.Join(call, ", "))
	fmt.Fprintf(b, "    %s\n  end\n\n", rubyDecode(doc, op.Result, "data"))
}

// rubyDecode turns a wire value into the typed object: a referenced class
// through from_h, an array element-wise, a primitive as-is.
func rubyDecode(doc *core.Document, s *core.Schema, expr string) string {
	if s == nil {
		return expr
	}
	if s.Ref != "" {
		target := doc.Components.Schemas[refName(s.Ref)]
		if target != nil && isStruct(target) && aliasTarget(target) == nil {
			p := pascalCase(refName(s.Ref))
			return fmt.Sprintf("(%s.from_h(%s) if %s)", p, expr, expr)
		}
		return rubyDecode(doc, target, expr)
	}
	if s.Type == "array" && s.Items != nil {
		inner := rubyDecode(doc, s.Items, "x")
		if inner == "x" {
			return fmt.Sprintf("(%s || [])", expr)
		}
		return fmt.Sprintf("(%s || []).map { |x| %s }", expr, inner)
	}
	return expr
}

// rubyDoc describes a non-class schema in a comment.
func rubyDoc(s *core.Schema) string {
	if s == nil {
		return "an untyped value"
	}
	if s.Ref != "" {
		return "a " + pascalCase(refName(s.Ref))
	}
	switch s.Type {
	case "array":
		return "an Array"
	case "object":
		return "a Hash"
	case "":
		return "an untyped value"
	default:
		return "a " + s.Type
	}
}

func rubyFieldName(name string) string  { return rubyIdent(snakeCase(name)) }
func rubyParamName(name string) string  { return rubyIdent(snakeCase(name)) }
func rubyMethodName(name string) string { return rubyIdent(snakeCase(name)) }

func rubyIdent(n string) string {
	if n == "" {
		return "field_"
	}
	switch n {
	case "class", "def", "end", "module", "begin", "do", "if", "else", "then",
		"self", "nil", "true", "false", "return", "next", "break", "in":
		return n + "_"
	}
	if n[0] >= '0' && n[0] <= '9' {
		return "f_" + n
	}
	return n
}
