package sdk

import (
	"fmt"
	"strings"

	"github.com/user/specter/internal/core"
)

// generateRust renders one self-contained lib.rs: a struct (or type alias) per
// schema and a Client with a typed method per operation, on reqwest's blocking
// client and serde. Fields are snake_case and carry a serde rename so the wire
// JSON keeps its original key names, while the Rust surface stays idiomatic.
func generateRust(doc *core.Document, opts Options) ([]File, error) {
	var b strings.Builder

	b.WriteString("// Code generated by specter. Edit freely — it is yours now.\n\n")
	b.WriteString("use serde::{Deserialize, Serialize};\n")
	b.WriteString("use std::collections::HashMap;\n\n")

	for _, name := range sortedSchemaNames(doc) {
		writeRustType(&b, doc, name, doc.Components.Schemas[name])
	}

	b.WriteString(`/// A non-2xx response. The decoded body, if any, is kept for inspection.
#[derive(Debug)]
pub struct ApiError {
    pub status: u16,
    pub body: Option<serde_json::Value>,
}

impl std::fmt::Display for ApiError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "request failed: {}", self.status)
    }
}

impl std::error::Error for ApiError {}

/// Either a non-2xx API response or a transport-level failure.
#[derive(Debug)]
pub enum Error {
    Api(ApiError),
    Http(String),
}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Error::Api(e) => write!(f, "{}", e),
            Error::Http(e) => write!(f, "http error: {}", e),
        }
    }
}

impl std::error::Error for Error {}

impl From<reqwest::Error> for Error {
    fn from(e: reqwest::Error) -> Self {
        Error::Http(e.to_string())
    }
}

/// Typed client for the API. Build one with Client::new, and attach a bearer
/// token with with_token when the API authenticates with one.
pub struct Client {
    base_url: String,
    token: Option<String>,
    http: reqwest::blocking::Client,
}

impl Client {
    pub fn new(base_url: impl Into<String>) -> Self {
        let mut url = base_url.into();
        while url.ends_with('/') {
            url.pop();
        }
        Client {
            base_url: url,
            token: None,
            http: reqwest::blocking::Client::new(),
        }
    }

    pub fn with_token(mut self, token: impl Into<String>) -> Self {
        self.token = Some(token.into());
        self
    }

    fn request<T: serde::de::DeserializeOwned>(
        &self,
        method: &str,
        path: &str,
        query: Option<&[(String, String)]>,
        body: Option<&serde_json::Value>,
    ) -> Result<T, Error> {
        let url = format!("{}{}", self.base_url, path);
        let verb = reqwest::Method::from_bytes(method.as_bytes())
            .map_err(|e| Error::Http(e.to_string()))?;
        let mut req = self.http.request(verb, &url);
        if let Some(q) = query {
            req = req.query(q);
        }
        if let Some(t) = &self.token {
            req = req.bearer_auth(t);
        }
        if let Some(payload) = body {
            req = req.json(payload);
        }
        let resp = req.send()?;
        let status = resp.status();
        let text = resp.text()?;
        let value: Option<serde_json::Value> = if text.is_empty() {
            None
        } else {
            serde_json::from_str(&text).ok()
        };
        if !status.is_success() {
            return Err(Error::Api(ApiError {
                status: status.as_u16(),
                body: value,
            }));
        }
        let data = value.unwrap_or(serde_json::Value::Null);
        serde_json::from_value(data).map_err(|e| Error::Http(e.to_string()))
    }

`)

	for _, op := range flatten(doc) {
		writeRustMethod(&b, op)
	}

	b.WriteString("}\n")
	return []File{{Name: "lib.rs", Data: []byte(b.String())}}, nil
}

func writeRustType(b *strings.Builder, doc *core.Document, name string, s *core.Schema) {
	if s == nil {
		return
	}
	typeName := pascalCase(name)
	// An allOf-of-one-ref is an alias for the type it composes.
	if a := aliasTarget(s); a != nil {
		fmt.Fprintf(b, "pub type %s = %s;\n\n", typeName, rustType(a))
		return
	}
	// A named schema that is not an object (an enum string, say) and composes
	// nothing becomes a plain type alias rather than a struct.
	if !isStruct(s) {
		fmt.Fprintf(b, "pub type %s = %s;\n\n", typeName, rustType(s))
		return
	}

	fields := resolvedFields(doc, s)
	b.WriteString("#[derive(Debug, Clone, Serialize, Deserialize)]\n")
	fmt.Fprintf(b, "pub struct %s {\n", typeName)
	for _, f := range fields {
		field := rustFieldName(f.Name)
		// Preserve the wire key when the idiomatic name differs.
		if field != f.Name {
			fmt.Fprintf(b, "    #[serde(rename = %q)]\n", f.Name)
		}
		ty := rustType(f.Schema)
		if !f.Required {
			b.WriteString("    #[serde(skip_serializing_if = \"Option::is_none\")]\n")
			ty = "Option<" + ty + ">"
		}
		fmt.Fprintf(b, "    pub %s: %s,\n", field, ty)
	}
	b.WriteString("}\n\n")
}

func writeRustMethod(b *strings.Builder, op operation) {
	var params []string
	for _, p := range op.PathParams {
		params = append(params, fmt.Sprintf("%s: &str", rustParamName(p)))
	}
	if op.Body != nil {
		params = append(params, "body: &"+rustType(op.Body))
	}
	if len(op.Query) > 0 {
		params = append(params, "query: &[(String, String)]")
	}

	result := "()"
	if op.Result != nil {
		result = rustType(op.Result)
	}

	b.WriteString("\n")
	if op.Summary != "" {
		fmt.Fprintf(b, "    /// %s\n", op.Summary)
	}
	if op.Deprecated {
		b.WriteString("    #[deprecated]\n")
	}
	fmt.Fprintf(b, "    pub fn %s(&self, %s) -> Result<%s, Error> {\n",
		rustMethodName(op.Name), strings.Join(params, ", "), result)

	// Build the path, interpolating any path parameters.
	path := op.Path
	hasParams := len(op.PathParams) > 0
	for _, p := range op.PathParams {
		path = strings.ReplaceAll(path, "{"+p+"}", "{"+rustParamName(p)+"}")
	}
	if hasParams {
		fmt.Fprintf(b, "        let path = format!(%q);\n", path)
	} else {
		fmt.Fprintf(b, "        let path = %q;\n", path)
	}

	pathArg := "&path"
	if !hasParams {
		pathArg = "path"
	}
	query := "None"
	if len(op.Query) > 0 {
		query = "Some(query)"
	}
	body := "None"
	if op.Body != nil {
		body = "Some(&serde_json::to_value(body).map_err(|e| Error::Http(e.to_string()))?)"
	}
	fmt.Fprintf(b, "        self.request(%q, %s, %s, %s)\n", op.Method, pathArg, query, body)
	b.WriteString("    }\n")
}

// rustType maps a JSON Schema fragment to a Rust type expression.
func rustType(s *core.Schema) string {
	if s == nil {
		return "serde_json::Value"
	}
	if s.Ref != "" {
		return pascalCase(refName(s.Ref))
	}
	switch s.Type {
	case "string":
		return "String"
	case "integer":
		return "i64"
	case "number":
		return "f64"
	case "boolean":
		return "bool"
	case "array":
		return "Vec<" + rustType(s.Items) + ">"
	case "object":
		if s.AdditionalProperties != nil {
			return "HashMap<String, " + rustType(s.AdditionalProperties) + ">"
		}
		return "serde_json::Value"
	}
	return "serde_json::Value"
}

// rustFieldName / rustParamName / rustMethodName keep identifiers legal and
// idiomatic, guarding the Rust keywords a name could collide with.
func rustFieldName(name string) string  { return rustIdent(snakeCase(name)) }
func rustParamName(name string) string  { return rustIdent(snakeCase(name)) }
func rustMethodName(name string) string { return rustIdent(snakeCase(name)) }

func rustIdent(n string) string {
	if n == "" {
		return "field_"
	}
	switch n {
	case "as", "break", "const", "continue", "crate", "dyn", "else", "enum",
		"extern", "false", "fn", "for", "if", "impl", "in", "let", "loop",
		"match", "mod", "move", "mut", "pub", "ref", "return", "self", "Self",
		"static", "struct", "super", "trait", "true", "type", "unsafe", "use",
		"where", "while", "async", "await", "box", "final", "macro",
		"override", "priv", "typeof", "unsized", "virtual", "yield", "try":
		return n + "_"
	}
	if n[0] >= '0' && n[0] <= '9' {
		return "f_" + n
	}
	return n
}
