package sdk

import (
	"fmt"
	"sort"
	"strings"

	"github.com/user/specter/internal/core"
)

// generateTS renders one self-contained client.ts: an interface per schema and
// a class with a typed method per operation, on top of fetch. No runtime
// dependency, so it drops into any project that has fetch — which is all of
// them.
func generateTS(doc *core.Document, opts Options) ([]File, error) {
	var b strings.Builder

	b.WriteString("// Code generated by specter. Edit freely — it is yours now.\n\n")

	for _, name := range sortedSchemaNames(doc) {
		writeTSInterface(&b, name, doc.Components.Schemas[name])
	}

	fmt.Fprintf(&b, "export interface ClientOptions {\n")
	fmt.Fprintf(&b, "  baseUrl?: string;\n")
	fmt.Fprintf(&b, "  /** Sent as `Authorization: Bearer <token>` when set. */\n")
	fmt.Fprintf(&b, "  token?: string;\n")
	fmt.Fprintf(&b, "  fetch?: typeof fetch;\n")
	fmt.Fprintf(&b, "}\n\n")

	fmt.Fprintf(&b, "export class ApiError extends Error {\n")
	fmt.Fprintf(&b, "  constructor(public status: number, public body: unknown) {\n")
	fmt.Fprintf(&b, "    super(`request failed: ${status}`);\n")
	fmt.Fprintf(&b, "  }\n}\n\n")

	fmt.Fprintf(&b, "export class Client {\n")
	fmt.Fprintf(&b, "  private baseUrl: string;\n")
	fmt.Fprintf(&b, "  private token?: string;\n")
	fmt.Fprintf(&b, "  private fetchImpl: typeof fetch;\n\n")
	fmt.Fprintf(&b, "  constructor(opts: ClientOptions = {}) {\n")
	fmt.Fprintf(&b, "    this.baseUrl = opts.baseUrl ?? %q;\n", opts.BaseURL)
	fmt.Fprintf(&b, "    this.token = opts.token;\n")
	fmt.Fprintf(&b, "    this.fetchImpl = opts.fetch ?? fetch;\n")
	fmt.Fprintf(&b, "  }\n\n")

	// One private request helper; every operation funnels through it.
	fmt.Fprintf(&b, "  private async request<T>(method: string, path: string, query?: Record<string, unknown>, body?: unknown): Promise<T> {\n")
	fmt.Fprintf(&b, "    const url = new URL(this.baseUrl + path);\n")
	fmt.Fprintf(&b, "    for (const [k, v] of Object.entries(query ?? {})) {\n")
	fmt.Fprintf(&b, "      if (v !== undefined && v !== null) url.searchParams.set(k, String(v));\n")
	fmt.Fprintf(&b, "    }\n")
	fmt.Fprintf(&b, "    const headers: Record<string, string> = {};\n")
	fmt.Fprintf(&b, "    if (body !== undefined) headers[\"Content-Type\"] = \"application/json\";\n")
	fmt.Fprintf(&b, "    if (this.token) headers[\"Authorization\"] = `Bearer ${this.token}`;\n")
	fmt.Fprintf(&b, "    const res = await this.fetchImpl(url, {\n")
	fmt.Fprintf(&b, "      method,\n")
	fmt.Fprintf(&b, "      headers,\n")
	fmt.Fprintf(&b, "      body: body === undefined ? undefined : JSON.stringify(body),\n")
	fmt.Fprintf(&b, "    });\n")
	fmt.Fprintf(&b, "    const text = await res.text();\n")
	fmt.Fprintf(&b, "    const data = text ? JSON.parse(text) : undefined;\n")
	fmt.Fprintf(&b, "    if (!res.ok) throw new ApiError(res.status, data);\n")
	fmt.Fprintf(&b, "    return data as T;\n")
	fmt.Fprintf(&b, "  }\n")

	for _, op := range flatten(doc) {
		writeTSMethod(&b, op)
	}

	b.WriteString("}\n")
	return []File{{Name: "client.ts", Data: []byte(b.String())}}, nil
}

func writeTSInterface(b *strings.Builder, name string, s *core.Schema) {
	if s == nil {
		return
	}
	// A named schema that is not an object (an enum string, say) becomes a
	// type alias rather than an interface.
	if s.Type != "object" || len(s.Properties) == 0 {
		fmt.Fprintf(b, "export type %s = %s;\n\n", name, tsType(s))
		return
	}
	required := map[string]bool{}
	for _, r := range s.Required {
		required[r] = true
	}
	fmt.Fprintf(b, "export interface %s {\n", name)
	props := make([]string, 0, len(s.Properties))
	for p := range s.Properties {
		props = append(props, p)
	}
	// Deterministic member order, same reason as everywhere else.
	sort.Strings(props)
	for _, p := range props {
		opt := "?"
		if required[p] {
			opt = ""
		}
		fmt.Fprintf(b, "  %s%s: %s;\n", tsPropName(p), opt, tsType(s.Properties[p]))
	}
	fmt.Fprintf(b, "}\n\n")
}

func writeTSMethod(b *strings.Builder, op operation) {
	var params []string
	for _, p := range op.PathParams {
		params = append(params, fmt.Sprintf("%s: string | number", tsParamName(p)))
	}
	if op.Body != nil {
		params = append(params, "body: "+tsType(op.Body))
	}
	if len(op.Query) > 0 {
		var q []string
		for _, p := range op.Query {
			q = append(q, fmt.Sprintf("%s?: %s", tsPropName(p.Name), tsType(p.Schema)))
		}
		params = append(params, fmt.Sprintf("query?: { %s }", strings.Join(q, "; ")))
	}

	result := "void"
	if op.Result != nil {
		result = tsType(op.Result)
	}

	b.WriteString("\n")
	if op.Summary != "" || op.Deprecated {
		fmt.Fprintf(b, "  /**\n")
		if op.Summary != "" {
			fmt.Fprintf(b, "   * %s\n", op.Summary)
		}
		if op.Deprecated {
			fmt.Fprintf(b, "   * @deprecated\n")
		}
		fmt.Fprintf(b, "   */\n")
	}
	fmt.Fprintf(b, "  %s(%s): Promise<%s> {\n", op.Name, strings.Join(params, ", "), result)

	path := op.Path
	for _, p := range op.PathParams {
		path = strings.ReplaceAll(path, "{"+p+"}", "${"+tsParamName(p)+"}")
	}
	query := "undefined"
	if len(op.Query) > 0 {
		query = "query"
	}
	body := "undefined"
	if op.Body != nil {
		body = "body"
	}
	fmt.Fprintf(b, "    return this.request<%s>(%q, `%s`, %s, %s);\n", result, op.Method, path, query, body)
	fmt.Fprintf(b, "  }\n")
}

// tsType maps a JSON Schema fragment to a TypeScript type expression.
func tsType(s *core.Schema) string {
	if s == nil {
		return "unknown"
	}
	if s.Ref != "" {
		return refName(s.Ref)
	}
	switch s.Type {
	case "string":
		if len(s.Enum) > 0 {
			var lits []string
			for _, e := range s.Enum {
				lits = append(lits, fmt.Sprintf("%q", fmt.Sprint(e)))
			}
			return strings.Join(lits, " | ")
		}
		return "string"
	case "integer", "number":
		return "number"
	case "boolean":
		return "boolean"
	case "array":
		return tsType(s.Items) + "[]"
	case "object":
		if s.AdditionalProperties != nil {
			return "Record<string, " + tsType(s.AdditionalProperties) + ">"
		}
		if len(s.Properties) > 0 {
			var props []string
			names := make([]string, 0, len(s.Properties))
			for p := range s.Properties {
				names = append(names, p)
			}
			sort.Strings(names)
			for _, p := range names {
				props = append(props, fmt.Sprintf("%s: %s", tsPropName(p), tsType(s.Properties[p])))
			}
			return "{ " + strings.Join(props, "; ") + " }"
		}
		return "Record<string, unknown>"
	}
	return "unknown"
}

// tsPropName quotes a property name that is not a legal identifier.
func tsPropName(name string) string {
	for i, r := range name {
		ok := r == '_' || r == '$' ||
			(r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') ||
			(i > 0 && r >= '0' && r <= '9')
		if !ok {
			return fmt.Sprintf("%q", name)
		}
	}
	if name == "" {
		return `""`
	}
	return name
}

// tsParamName makes a path parameter usable as an argument name.
func tsParamName(name string) string {
	n := exportName(name)
	if n == "" {
		return "param"
	}
	return strings.ToLower(n[:1]) + n[1:]
}
