package admin

import (
	"bytes"
	"embed"
	"fmt"
	"go/format"
	"strconv"
	"strings"
	"text/template"

	"github.com/user/specter/internal/core"
)

//go:embed templates/*.tmpl
var assets embed.FS

// Options configures generation.
type Options struct {
	// Package is the generated package name; "admin" by default.
	Package string
	// Prefix is where the panel expects to be mounted; "/admin" by default.
	Prefix string
	// BaseURL is the API the panel calls. It can be changed at runtime through
	// Config, so this is only the default written into the generated code.
	BaseURL string
	// ImportPath is the generated package's import path, needed only for the
	// standalone entrypoint. When it is empty no entrypoint is written, since a
	// main.go that imports a path that does not resolve would not build.
	ImportPath string
	// Dir is the output directory, used in the entrypoint's usage comment.
	Dir string
}

// File is one generated file, named relative to the output directory.
type File struct {
	Name string
	Data []byte
}

// Generate turns a document into an admin panel: a gin-mounted package of Go
// handlers and html/template views.
//
// The output is source, not a runtime. That is deliberate — an admin panel is
// where per-project judgement lives (which column matters, which field is a
// secret, what "archived" means), and none of that is in an OpenAPI document.
// Generating source means the first version is free and every version after it
// is yours to edit.
func Generate(doc *core.Document, opts Options) ([]File, error) {
	if opts.Package == "" {
		opts.Package = "admin"
	}
	if opts.Prefix == "" {
		opts.Prefix = "/admin"
	}

	m := Build(doc)
	if len(m.Resources) == 0 {
		return nil, fmt.Errorf("no resources found: an admin panel needs at least one collection with a list endpoint (GET /things)")
	}
	if opts.BaseURL == "" {
		opts.BaseURL = m.BaseURL
	}
	if opts.BaseURL == "" {
		opts.BaseURL = "http://localhost:8080"
	}

	runtime, err := render("runtime.go.tmpl", map[string]any{"Package": opts.Package})
	if err != nil {
		return nil, err
	}
	runtime, err = gofmt("runtime.go", runtime)
	if err != nil {
		return nil, err
	}

	resources, err := gofmt("resources.go", []byte(resourcesSource(m, opts)))
	if err != nil {
		return nil, err
	}

	files := []File{
		{"admin.go", runtime},
		{"resources.go", resources},
	}

	// The standalone entrypoint gives the panel its own router and its own
	// port, so it can be run without touching the service it administers.
	if opts.ImportPath != "" {
		dir := opts.Dir
		if dir == "" {
			dir = "admin"
		}
		entry, err := render("main.go.tmpl", map[string]any{
			"ImportPath": opts.ImportPath,
			"Dir":        strings.Trim(dir, "./"),
		})
		if err != nil {
			return nil, err
		}
		if entry, err = gofmt("cmd/adminpanel/main.go", entry); err != nil {
			return nil, err
		}
		files = append(files, File{"cmd/adminpanel/main.go", entry})
	}

	// The view templates are copied through unchanged; they are the part a
	// project is most likely to restyle.
	for _, name := range []string{"layout", "list", "detail", "form", "login"} {
		data, err := assets.ReadFile("templates/" + name + ".html.tmpl")
		if err != nil {
			return nil, err
		}
		files = append(files, File{"templates/" + name + ".html", data})
	}
	return files, nil
}

func render(name string, data any) ([]byte, error) {
	t, err := template.ParseFS(assets, "templates/"+name)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// gofmt formats generated source. A failure here is a bug in the generator
// rather than in the user's project, so the error names the file and keeps the
// unformatted source out of the output entirely — writing code that does not
// compile would be worse than writing nothing.
func gofmt(name string, src []byte) ([]byte, error) {
	out, err := format.Source(src)
	if err != nil {
		return nil, fmt.Errorf("admin: generated %s does not parse: %w", name, err)
	}
	return out, nil
}

// resourcesSource writes the model as Go source. Generating a literal rather
// than shipping JSON to be parsed at startup means a resource that does not
// compile fails at build time, and the panel has no startup failure mode.
func resourcesSource(m Model, opts Options) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by specter -admin. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "//\n// Regenerate with: specter -admin -o <dir>\n")
	fmt.Fprintf(&b, "// Edits here are lost on the next run; admin.go and templates/ are yours.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", opts.Package)
	fmt.Fprintf(&b, "// Title is the API this panel administers.\nconst Title = %s\n\n", strconv.Quote(m.Title))
	fmt.Fprintf(&b, "// DefaultBaseURL is where the API was found when this was generated.\nconst DefaultBaseURL = %s\n\n", strconv.Quote(opts.BaseURL))
	fmt.Fprintf(&b, "// DefaultPrefix is where the panel expects to be mounted.\nconst DefaultPrefix = %s\n\n", strconv.Quote(opts.Prefix))

	fmt.Fprintf(&b, "// Resources is every collection the API exposes a list endpoint for,\n")
	fmt.Fprintf(&b, "// with only the actions its endpoints actually support.\n")
	fmt.Fprintf(&b, "var Resources = []Resource{\n")
	for _, r := range m.Resources {
		fmt.Fprintf(&b, "\t{\n")
		fmt.Fprintf(&b, "\t\tName: %s, Label: %s, Singular: %s,\n",
			strconv.Quote(r.Name), strconv.Quote(r.Label), strconv.Quote(r.Singular))
		fmt.Fprintf(&b, "\t\tCollectionPath: %s, ItemPath: %s, IDParam: %s,\n",
			strconv.Quote(r.CollectionPath), strconv.Quote(r.ItemPath), strconv.Quote(r.IDParam))
		writeAction(&b, "List", r.List)
		writeAction(&b, "Get", r.Get)
		writeAction(&b, "Create", r.Create)
		writeAction(&b, "Update", r.Update)
		writeAction(&b, "Delete", r.Delete)
		writeFields(&b, "Fields", r.Fields)
		writeFields(&b, "Form", r.Form)
		fmt.Fprintf(&b, "\t},\n")
	}
	fmt.Fprintf(&b, "}\n")
	return b.String()
}

func writeAction(b *strings.Builder, name string, a *Action) {
	if a == nil {
		return
	}
	fmt.Fprintf(b, "\t\t%s: &Action{Method: %s, Path: %s, Label: %s, Handler: %s",
		name, strconv.Quote(a.Method), strconv.Quote(a.Path),
		strconv.Quote(a.Label), strconv.Quote(a.Handler))
	if a.Summary != "" {
		fmt.Fprintf(b, ", Summary: %s", strconv.Quote(a.Summary))
	}
	if a.Secured {
		fmt.Fprintf(b, ", Secured: true")
	}
	if len(a.Headers) > 0 {
		fmt.Fprintf(b, ", Headers: %s", quoteSlice(a.Headers))
	}
	fmt.Fprintf(b, "},\n")
}

func writeFields(b *strings.Builder, name string, fields []Field) {
	if len(fields) == 0 {
		return
	}
	fmt.Fprintf(b, "\t\t%s: []Field{\n", name)
	for _, f := range fields {
		fmt.Fprintf(b, "\t\t\t{Name: %s, Label: %s", strconv.Quote(f.Name), strconv.Quote(f.Label))
		if f.Type != "" {
			fmt.Fprintf(b, ", Type: %s", strconv.Quote(f.Type))
		}
		if f.Format != "" {
			fmt.Fprintf(b, ", Format: %s", strconv.Quote(f.Format))
		}
		if f.Required {
			fmt.Fprintf(b, ", Required: true")
		}
		if f.Primary {
			fmt.Fprintf(b, ", Primary: true")
		}
		if f.Ref != "" {
			fmt.Fprintf(b, ", Ref: %s", strconv.Quote(f.Ref))
		}
		if f.Image {
			fmt.Fprintf(b, ", Image: true")
		}
		if len(f.Enum) > 0 {
			fmt.Fprintf(b, ", Enum: %s", quoteSlice(f.Enum))
		}
		fmt.Fprintf(b, "},\n")
	}
	fmt.Fprintf(b, "\t\t},\n")
}

func quoteSlice(items []string) string {
	parts := make([]string, len(items))
	for i, s := range items {
		parts[i] = strconv.Quote(s)
	}
	return "[]string{" + strings.Join(parts, ", ") + "}"
}
