// Code generated by specter -admin. Edit freely.
//
// A standalone admin panel: its own router, its own port, its own process.
// It talks to your API over HTTP like any other client, so it needs no access
// to your database and nothing in your service has to change to run it.
//
//	go run ./examples/shop/admin/cmd/adminpanel -api http://localhost:8080 -addr :9090
package main

import (
	"flag"
	"fmt"
	"log"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/gin-gonic/gin"

	admin "github.com/user/specter/examples/shop/admin"
)

func main() {
	api := flag.String("api", admin.DefaultBaseURL, "base URL of the API to administer")
	addr := flag.String("addr", ":9090", "address to serve the panel on")
	prefix := flag.String("prefix", admin.DefaultPrefix, "path the panel is served under")
	header := flag.String("header", "", "header to send upstream, repeatable as name:value,name:value")
	uploads := flag.String("uploads", "", "directory to store uploaded images in; empty disables uploads")
	public := flag.String("public-url", "", "base URL uploaded images are addressed by (default: served by the panel)")
	user := flag.String("user", os.Getenv("ADMIN_USER"), "username for the login form (also ADMIN_USER)")
	pass := flag.String("password", os.Getenv("ADMIN_PASSWORD"), "password for the login form (also ADMIN_PASSWORD)")
	token := flag.String("token", os.Getenv("ADMIN_TOKEN"), "bearer token; when set, the panel is headless and requires it on every request (also ADMIN_TOKEN)")
	sessionKey := flag.String("session-key", os.Getenv("ADMIN_SESSION_KEY"), "key that signs the login cookie; random if empty (also ADMIN_SESSION_KEY)")
	flag.Parse()

	headers := map[string]string{}
	for _, pair := range strings.Split(*header, ",") {
		pair = strings.TrimSpace(pair)
		if pair == "" {
			continue
		}
		name, value, ok := strings.Cut(pair, ":")
		if !ok {
			log.Fatalf("bad -header %q: want name:value", pair)
		}
		headers[strings.TrimSpace(name)] = strings.TrimSpace(value)
	}

	gin.SetMode(gin.ReleaseMode)
	r := gin.New()
	r.Use(gin.Recovery())

	if err := admin.Mount(r, admin.Config{
		BaseURL:    *api,
		Prefix:     *prefix,
		Headers:    headers,
		UploadDir:  *uploads,
		PublicURL:  *public,
		Username:   *user,
		Password:   *pass,
		Token:      *token,
		SessionKey: *sessionKey,
	}); err != nil {
		log.Fatal(err)
	}

	// A bare / is a dead end otherwise, and the panel's own prefix is not
	// guessable from a browser address bar.
	r.GET("/", func(c *gin.Context) { c.Redirect(http.StatusFound, *prefix) })

	fmt.Fprintf(os.Stderr, "admin: %d resources\n", len(admin.Resources))
	fmt.Fprintf(os.Stderr, "admin: serving http://localhost%s%s\n", *addr, *prefix)
	fmt.Fprintf(os.Stderr, "admin: calling %s\n", *api)
	if *uploads != "" {
		fmt.Fprintf(os.Stderr, "admin: uploads stored in %s\n", *uploads)
	}
	if len(headers) == 0 && secured() {
		fmt.Fprintln(os.Stderr, "admin: this API is guarded and no -header was set; expect 401s")
	}
	switch {
	case *token != "":
		fmt.Fprintln(os.Stderr, "admin: protected by a bearer token; every request must carry it")
	case *user != "" || *pass != "":
		fmt.Fprintln(os.Stderr, "admin: protected by a login form")
	default:
		fmt.Fprintln(os.Stderr, "admin: WARNING — no -user/-password or -token set; the panel is open to anyone who can reach it")
	}

	srv := &http.Server{
		Addr:              *addr,
		Handler:           r,
		ReadHeaderTimeout: 10 * time.Second,
	}
	log.Fatal(srv.ListenAndServe())
}

// secured reports whether any resource sits behind authentication, so an
// operator who will certainly get 401s is told before they see them.
func secured() bool {
	for _, r := range admin.Resources {
		if r.List != nil && (r.List.Secured || len(r.List.Headers) > 0) {
			return true
		}
	}
	return false
}
