package contract

import (
	"fmt"
	"strconv"
	"strings"
)

// renderCurl writes a POSIX shell smoke test.
//
// It checks status codes and nothing else, which is the point: a pipeline that
// has curl and nothing else installed can still answer "is every documented
// endpoint there and answering something the document allows". Body shape is
// the Go test's job, where there is a language to express it in.
func renderCurl(reqs []request, opts Options, a *auth) []byte {
	var b strings.Builder

	b.WriteString("#!/bin/sh\n")
	b.WriteString("# Generated by specter. Calls every documented endpoint and checks the\n")
	b.WriteString("# status code against what the document says it can answer.\n")
	b.WriteString("#\n")
	b.WriteString("# Every documented status counts as a pass — a 404 the document promises\n")
	b.WriteString("# is the endpoint behaving, not failing.\n")
	b.WriteString("set -u\n\n")
	fmt.Fprintf(&b, "BASE=\"${SPECTER_BASE_URL:-%s}\"\n", opts.BaseURL)
	if a != nil {
		fmt.Fprintf(&b, "%s=\"${%s:-}\"\n", a.Variable, a.Env)
	}
	b.WriteString("failed=0\n\n")

	// check is a function rather than repeated inline curl so the output stays
	// readable when a suite has fifty endpoints.
	b.WriteString(`check() {
  method="$1"; path="$2"; expected="$3"; body="${4:-}"
  if [ -n "$body" ]; then
    code=$(curl -s -o /dev/null -w '%{http_code}' -X "$method" "$BASE$path" \
      -H 'Content-Type: application/json' ${EXTRA_HEADER:+-H "$EXTRA_HEADER"} -d "$body")
  else
    code=$(curl -s -o /dev/null -w '%{http_code}' -X "$method" "$BASE$path" \
      ${EXTRA_HEADER:+-H "$EXTRA_HEADER"})
  fi
  for want in $expected; do
    if [ "$code" = "$want" ]; then
      echo "ok    $method $path -> $code"
      return 0
    fi
  done
  echo "FAIL  $method $path -> $code (documented: $expected)"
  failed=$((failed + 1))
}

`)

	if a != nil {
		fmt.Fprintf(&b, "EXTRA_HEADER=\"\"\n")
		fmt.Fprintf(&b, "[ -n \"$%s\" ] && EXTRA_HEADER=\"%s: %s$%s\"\n\n", a.Variable, a.Header, a.Prefix, a.Variable)
	} else {
		b.WriteString("EXTRA_HEADER=\"\"\n\n")
	}

	for _, r := range reqs {
		fmt.Fprintf(&b, "# %s\n", r.Name)
		args := []string{shellQuote(r.Method), shellQuote(r.Path + queryString(r)), shellQuote(statusWords(r.Statuses))}
		if len(r.Body) > 0 {
			args = append(args, shellQuote(compactBody(r.Body)))
		}
		fmt.Fprintf(&b, "check %s\n\n", strings.Join(args, " "))
	}

	b.WriteString(`if [ "$failed" -gt 0 ]; then
  echo
  echo "$failed endpoint(s) did not match the document."
  exit 1
fi
echo
echo "every endpoint matched the document."
`)
	return []byte(b.String())
}

func statusWords(codes []int) string {
	parts := make([]string, len(codes))
	for i, c := range codes {
		parts[i] = strconv.Itoa(c)
	}
	return strings.Join(parts, " ")
}

// compactBody puts a JSON body on one line so it survives being a shell
// argument without quoting games.
func compactBody(body []byte) string {
	var b strings.Builder
	for _, line := range strings.Split(string(body), "\n") {
		b.WriteString(strings.TrimSpace(line))
	}
	return b.String()
}

// shellQuote wraps a value in single quotes, which the shell takes literally,
// escaping any single quote inside it.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}
