package contract

import (
	"fmt"
	"strings"
)

// renderHTTP writes the .http file that VS Code's REST Client and the
// JetBrains HTTP client both read.
//
// It is the artefact with the shortest path to being useful: open it, click
// Send, see the endpoint answer. Variables sit at the top so the whole file
// retargets by editing one line, which is what makes it worth committing next
// to the code rather than regenerating each time.
func renderHTTP(reqs []request, opts Options, a *auth) []byte {
	var b strings.Builder

	b.WriteString("# Generated by specter. Requests for every documented endpoint.\n")
	b.WriteString("# Edit @baseUrl to point somewhere else; every request follows.\n\n")
	fmt.Fprintf(&b, "@baseUrl = %s\n", opts.BaseURL)
	if a != nil {
		fmt.Fprintf(&b, "@%s =\n", a.Variable)
	}
	b.WriteString("\n")

	for _, r := range reqs {
		fmt.Fprintf(&b, "### %s\n", r.Name)
		fmt.Fprintf(&b, "%s {{baseUrl}}%s%s\n", r.Method, r.Path, queryString(r))

		for _, h := range r.Headers {
			fmt.Fprintf(&b, "%s: %s\n", h.Key, h.Value)
		}
		if a != nil {
			fmt.Fprintf(&b, "%s: %s{{%s}}\n", a.Header, a.Prefix, a.Variable)
		}
		if len(r.Body) > 0 {
			b.WriteString("Content-Type: application/json\n\n")
			b.Write(r.Body)
			b.WriteString("\n")
		}
		b.WriteString("\n")
	}
	return []byte(b.String())
}

// queryString renders the required query parameters. Values come from the
// schema, so they are the kind of value the endpoint accepts rather than a
// placeholder that has to be replaced before the request will run.
func queryString(r request) string {
	if len(r.Query) == 0 {
		return ""
	}
	parts := make([]string, len(r.Query))
	for i, q := range r.Query {
		parts[i] = q.Key + "=" + q.Value
	}
	return "?" + strings.Join(parts, "&")
}
