package testgen

import (
	"go/parser"
	"go/token"
	"strings"
	"testing"

	"github.com/user/specter/internal/core"
)

// mustParse asserts the generated file is legal Go, not merely text that looks
// like it — the whole value of the generator is that the output compiles.
func mustParse(t *testing.T, src []byte) {
	t.Helper()
	if _, err := parser.ParseFile(token.NewFileSet(), "api_test.go", src, 0); err != nil {
		t.Fatalf("generated file does not parse: %v\n%s", err, src)
	}
}

// funcBody returns the text of the named generated test function, so a test
// can assert about one operation without matching the rest of the file.
func funcBody(t *testing.T, src, name string) string {
	t.Helper()
	i := strings.Index(src, "func "+name+"(t *testing.T) {")
	if i < 0 {
		t.Fatalf("generated file has no %s", name)
	}
	rest := src[i:]
	if end := strings.Index(rest, "\n}\n"); end >= 0 {
		return rest[:end]
	}
	return rest
}

// An empty document still produces a compiling file: the harness (baseURL,
// doJSON, contains) is emitted unconditionally, and the default package name
// applies.
func TestEmptyDocument(t *testing.T) {
	src := Generate(core.NewDocument("Empty API", "1.0.0"), Options{})
	mustParse(t, src)

	s := string(src)
	for _, want := range []string{
		"package apitest",
		`Code generated by specter from "Empty API"`,
		"func baseURL(t *testing.T) string {",
		"func doJSON(t *testing.T, method, url string, body []byte, allowed map[int]bool) {",
		"func contains(s, sub string) bool {",
		"SPECTER_BASE_URL",
	} {
		if !strings.Contains(s, want) {
			t.Errorf("output missing %q", want)
		}
	}
	if strings.Contains(s, "func Test") {
		t.Error("an empty document should produce no tests")
	}
}

// An explicit package name overrides the default.
func TestPackageOption(t *testing.T) {
	src := Generate(core.NewDocument("API", "1.0.0"), Options{Package: "usersapi"})
	mustParse(t, src)
	if !strings.Contains(string(src), "package usersapi") {
		t.Error("Package option not honoured")
	}
}

// Paths are sorted and methods follow the conventional CRUD order, so
// regenerating an unchanged document produces a byte-identical file.
func TestDeterministicOrder(t *testing.T) {
	d := core.NewDocument("API", "1.0.0")
	d.AddOperation("/zebras", "get", &core.Operation{OperationID: "listZebras"})
	d.AddOperation("/apples", "delete", &core.Operation{OperationID: "deleteApple"})
	d.AddOperation("/apples", "post", &core.Operation{OperationID: "createApple"})
	d.AddOperation("/apples", "get", &core.Operation{OperationID: "listApples"})

	first := string(Generate(d, Options{}))
	mustParse(t, []byte(first))

	if second := string(Generate(d, Options{})); first != second {
		t.Error("two runs over the same document disagree")
	}

	want := []string{"TestListApples", "TestCreateApple", "TestDeleteApple", "TestListZebras"}
	at := -1
	for _, name := range want {
		i := strings.Index(first, "func "+name+"(")
		if i < 0 {
			t.Fatalf("missing %s", name)
		}
		if i < at {
			t.Errorf("%s is out of order", name)
		}
		at = i
	}
}

// Path parameters must be substituted so the URL is syntactically valid,
// whatever form the parameter takes: inline, behind a component $ref, or with
// no schema at all.
func TestPathParameterSubstitution(t *testing.T) {
	d := core.NewDocument("API", "1.0.0")
	d.Components.Parameters = map[string]*core.Parameter{}
	d.Components.Parameters["IdParam"] = &core.Parameter{
		Name: "id", In: "path", Schema: &core.Schema{Type: "integer", Example: 42},
	}
	d.Components.Parameters["Nil"] = nil // present in the map but empty

	d.AddOperation("/a/{id}", "get", &core.Operation{
		OperationID: "refParam",
		Parameters:  []core.Parameter{{Ref: "#/components/parameters/IdParam"}},
	})
	d.AddOperation("/b/{slug}", "get", &core.Operation{
		OperationID: "inlineParam",
		Parameters: []core.Parameter{
			{Name: "slug", In: "path", Schema: &core.Schema{Type: "string", Example: "hello"}},
			// A query parameter is not part of the URL template.
			{Name: "q", In: "query", Schema: &core.Schema{Type: "string"}},
			// A path parameter with no name cannot be substituted.
			{Name: "", In: "path", Schema: &core.Schema{Type: "string"}},
		},
	})
	d.AddOperation("/c/{id}", "get", &core.Operation{
		OperationID: "noSchema",
		// No schema means no sample, so the generator falls back to "1".
		Parameters: []core.Parameter{{Name: "id", In: "path"}},
	})
	d.AddOperation("/d/{id}", "get", &core.Operation{
		OperationID: "danglingRef",
		// A $ref that resolves to nil yields an empty parameter, which is
		// skipped rather than substituted.
		Parameters: []core.Parameter{{Ref: "#/components/parameters/Nil"}},
	})
	d.AddOperation("/e/{id}", "get", &core.Operation{
		OperationID: "missingRef",
		Parameters:  []core.Parameter{{Ref: "#/components/parameters/Absent"}},
	})

	src := Generate(d, Options{})
	mustParse(t, src)
	s := string(src)

	for _, want := range []string{
		`"/a/42"`,    // from the component parameter's example
		`"/b/hello"`, // from the inline example
		`"/c/1"`,     // schema-less fallback
		`"/d/{id}"`,  // unresolvable ref: template left alone
		`"/e/{id}"`,  // missing ref: same
		`"GET"`,
	} {
		if !strings.Contains(s, want) {
			t.Errorf("output missing %q", want)
		}
	}
}

// A JSON request body becomes a literal in the test; anything else leaves the
// request bodiless.
func TestRequestBodies(t *testing.T) {
	d := core.NewDocument("API", "1.0.0")
	d.AddOperation("/json", "post", &core.Operation{
		OperationID: "withJSON",
		RequestBody: &core.RequestBody{Content: map[string]core.MediaType{
			"application/json": {Schema: &core.Schema{
				Type:       "object",
				Properties: map[string]*core.Schema{"name": {Type: "string", Example: "ada"}},
				Required:   []string{"name"},
			}},
		}},
		Responses: map[string]*core.Response{"201": {}},
	})
	d.AddOperation("/form", "post", &core.Operation{
		OperationID: "withForm",
		// Not JSON, so nothing to send.
		RequestBody: &core.RequestBody{Content: map[string]core.MediaType{
			"application/x-www-form-urlencoded": {Schema: &core.Schema{Type: "object"}},
		}},
	})
	d.AddOperation("/nilschema", "post", &core.Operation{
		OperationID: "withNilSchema",
		RequestBody: &core.RequestBody{Content: map[string]core.MediaType{
			"application/json": {}, // declared, but no schema
		}},
	})

	src := Generate(d, Options{})
	mustParse(t, src)
	s := string(src)

	if !strings.Contains(s, "body := []byte(`") || !strings.Contains(s, `"ada"`) {
		t.Error("JSON request body not emitted")
	}
	if !strings.Contains(s, ", body, allowed)") {
		t.Error("the JSON operation should pass its body")
	}
	for _, name := range []string{"TestWithForm", "TestWithNilSchema"} {
		fn := funcBody(t, s, name)
		if strings.Contains(fn, "body := []byte(") {
			t.Errorf("%s should be bodiless:\n%s", name, fn)
		}
		if !strings.Contains(fn, ", nil, allowed)") {
			t.Errorf("%s should pass a nil body:\n%s", name, fn)
		}
	}
}

// A backtick in the sampled body would end the raw string literal, so it is
// replaced rather than escaped.
func TestBacktickInBodyDoesNotBreakTheLiteral(t *testing.T) {
	d := core.NewDocument("API", "1.0.0")
	d.AddOperation("/x", "post", &core.Operation{
		OperationID: "tricky",
		RequestBody: &core.RequestBody{Content: map[string]core.MediaType{
			"application/json": {Schema: &core.Schema{
				Type:       "object",
				Properties: map[string]*core.Schema{"code": {Type: "string", Example: "a`b"}},
				Required:   []string{"code"},
			}},
		}},
	})
	src := Generate(d, Options{})
	mustParse(t, src) // the real assertion: still legal Go
	if strings.Contains(string(src), "a`b") {
		t.Error("backtick survived into the raw string literal")
	}
}

// Only numeric response codes make it into the allowed set, sorted; "default"
// and friends are not statuses.
func TestAllowedStatusCodes(t *testing.T) {
	d := core.NewDocument("API", "1.0.0")
	d.AddOperation("/x", "get", &core.Operation{
		OperationID: "codes",
		Responses: map[string]*core.Response{
			"404":     {},
			"200":     {},
			"default": {}, // not a status at all
		},
	})
	d.AddOperation("/y", "get", &core.Operation{OperationID: "noCodes"})

	s := string(Generate(d, Options{}))
	mustParse(t, []byte(s))

	if !strings.Contains(s, "allowed := map[int]bool{200: true, 404: true}") {
		t.Error("numeric codes not collected in sorted order")
	}
	if !strings.Contains(s, "allowed := map[int]bool{}") {
		t.Error("an operation with no responses should get an empty allowed set")
	}
}

// testName has to produce a unique, legal Go identifier from anything the
// document offers.
func TestTestName(t *testing.T) {
	used := map[string]int{}

	cases := []struct {
		desc   string
		method string
		path   string
		op     *core.Operation
		want   string
	}{
		{"operationId wins", "get", "/users", &core.Operation{OperationID: "listUsers"}, "TestListUsers"},
		{"derived from method and path", "get", "/api/v1/users/{id}", &core.Operation{}, "TestGetApiV1UsersId"},
		{"punctuation splits words", "post", "/", &core.Operation{OperationID: "do-a_thing.now"}, "TestDoAThingNow"},
		{"non-ASCII is a separator", "get", "/", &core.Operation{OperationID: "naïve"}, "TestNaVe"},
		{"nothing usable leaves the bare prefix", "get", "/", &core.Operation{OperationID: "-–-"}, "Test"},
	}
	for _, tc := range cases {
		if got := testName(used, tc.method, tc.path, tc.op); got != tc.want {
			t.Errorf("%s: testName = %q, want %q", tc.desc, got, tc.want)
		}
	}

	// A repeat of an earlier name gets a numeric suffix, and so does the one
	// after that.
	op := &core.Operation{OperationID: "listUsers"}
	if got := testName(used, "get", "/users", op); got != "TestListUsers2" {
		t.Errorf("second collision = %q, want TestListUsers2", got)
	}
	if got := testName(used, "get", "/users", op); got != "TestListUsers3" {
		t.Errorf("third collision = %q, want TestListUsers3", got)
	}
}

// End to end: two operations that derive the same test name must still yield a
// file that compiles, which is what the suffixing exists for.
func TestCollidingNamesStillCompile(t *testing.T) {
	d := core.NewDocument("API", "1.0.0")
	d.AddOperation("/a-b", "get", &core.Operation{})
	d.AddOperation("/a/b", "get", &core.Operation{})

	src := Generate(d, Options{})
	mustParse(t, src)
	s := string(src)
	if !strings.Contains(s, "func TestGetAB(t *testing.T)") || !strings.Contains(s, "func TestGetAB2(t *testing.T)") {
		t.Errorf("expected suffixed duplicate test names, got:\n%s", s)
	}
}

// resolveParamRef is the one place a $ref is followed; each outcome matters.
func TestResolveParamRef(t *testing.T) {
	d := core.NewDocument("API", "1.0.0")
	d.Components.Parameters = map[string]*core.Parameter{}
	d.Components.Parameters["Page"] = &core.Parameter{Name: "page", In: "query"}
	d.Components.Parameters["Broken"] = nil

	if got := resolveParamRef(d, core.Parameter{Name: "inline", In: "path"}); got.Name != "inline" {
		t.Errorf("a parameter with no $ref should be returned unchanged, got %+v", got)
	}
	if got := resolveParamRef(d, core.Parameter{Ref: "#/components/parameters/Page"}); got.Name != "page" {
		t.Errorf("resolved = %+v, want the page parameter", got)
	}
	if got := resolveParamRef(d, core.Parameter{Ref: "#/components/parameters/Broken"}); got.Name != "" {
		t.Errorf("a nil component should resolve to the zero parameter, got %+v", got)
	}
	if got := resolveParamRef(d, core.Parameter{Ref: "#/components/parameters/Missing"}); got.Name != "" {
		t.Errorf("an absent component should resolve to the zero parameter, got %+v", got)
	}
}

// sortedMethods puts unknown verbs first (order 0, alongside get) but never
// panics or drops them; sortedPaths is a plain lexical sort.
func TestSortedHelpers(t *testing.T) {
	d := core.NewDocument("API", "1.0.0")
	d.AddOperation("/b", "get", &core.Operation{})
	d.AddOperation("/a", "get", &core.Operation{})

	paths := sortedPaths(d)
	if len(paths) != 2 || paths[0] != "/a" || paths[1] != "/b" {
		t.Errorf("sortedPaths = %v", paths)
	}

	ops := map[string]*core.Operation{
		"delete": {}, "get": {}, "post": {}, "options": {}, "put": {}, "patch": {}, "head": {},
	}
	got := sortedMethods(ops)
	want := []string{"get", "post", "put", "patch", "delete", "head", "options"}
	for i := range want {
		if got[i] != want[i] {
			t.Fatalf("sortedMethods = %v, want %v", got, want)
		}
	}
}
