// Package testgen writes Go integration tests from a generated document.
//
// Each documented operation becomes one test that sends a real HTTP request —
// path parameters and request bodies filled from the document's examples and
// schemas — and asserts the response status is one the document declares and
// the body parses as JSON when the document says it is JSON.
//
// The tests hit a live server named by SPECTER_BASE_URL, because an
// integration test against a mock of the same document proves nothing: the
// document would be checked against itself. Without the variable set the
// tests skip rather than fail, so the file is safe to commit and run in any
// suite.
package testgen

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/user/specter/internal/core"
	"github.com/user/specter/internal/mock"
)

// Options configures the generated file.
type Options struct {
	// Package is the package name of the generated file. Empty means "apitest".
	Package string
}

// Generate renders the test file. The result is one self-contained _test.go
// file with no imports beyond the standard library, so dropping it into a
// project adds no dependency.
func Generate(doc *core.Document, opts Options) []byte {
	pkg := opts.Package
	if pkg == "" {
		pkg = "apitest"
	}

	var b strings.Builder
	fmt.Fprintf(&b, `// Code generated by specter from %q. Edit freely — it is a starting point.
//
// Set SPECTER_BASE_URL to the server under test (e.g. http://localhost:8080).
// Unset, every test skips, so this file is safe in any suite.
package %s

import (
	"bytes"
	"encoding/json"
	"io"
	"net/http"
	"os"
	"testing"
	"time"
)

func baseURL(t *testing.T) string {
	t.Helper()
	u := os.Getenv("SPECTER_BASE_URL")
	if u == "" {
		t.Skip("SPECTER_BASE_URL not set")
	}
	for len(u) > 0 && u[len(u)-1] == '/' {
		u = u[:len(u)-1]
	}
	return u
}

var apiClient = &http.Client{Timeout: 10 * time.Second}

// doJSON sends the request and checks the response against the documented
// statuses; when the response claims to be JSON it must parse as JSON.
func doJSON(t *testing.T, method, url string, body []byte, allowed map[int]bool) {
	t.Helper()
	var rd io.Reader
	if body != nil {
		rd = bytes.NewReader(body)
	}
	req, err := http.NewRequest(method, url, rd)
	if err != nil {
		t.Fatalf("build request: %%v", err)
	}
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	if tok := os.Getenv("SPECTER_BEARER_TOKEN"); tok != "" {
		req.Header.Set("Authorization", "Bearer "+tok)
	}
	resp, err := apiClient.Do(req)
	if err != nil {
		t.Fatalf("%%s %%s: %%v", method, url, err)
	}
	defer resp.Body.Close()
	if len(allowed) > 0 && !allowed[resp.StatusCode] {
		t.Errorf("%%s %%s: status %%d not documented", method, url, resp.StatusCode)
	}
	data, err := io.ReadAll(resp.Body)
	if err != nil {
		t.Fatalf("read body: %%v", err)
	}
	if ct := resp.Header.Get("Content-Type"); len(data) > 0 && contains(ct, "json") {
		var v any
		if err := json.Unmarshal(data, &v); err != nil {
			t.Errorf("%%s %%s: Content-Type says JSON but body does not parse: %%v", method, url, err)
		}
	}
}

func contains(s, sub string) bool {
	for i := 0; i+len(sub) <= len(s); i++ {
		if s[i:i+len(sub)] == sub {
			return true
		}
	}
	return false
}
`, doc.Info.Title, pkg)

	usedNames := map[string]int{}
	for _, path := range sortedPaths(doc) {
		for _, method := range sortedMethods(doc.Paths[path]) {
			op := doc.Paths[path][method]
			writeTest(&b, doc, usedNames, path, method, op)
		}
	}
	return []byte(b.String())
}

func writeTest(b *strings.Builder, doc *core.Document, used map[string]int, path, method string, op *core.Operation) {
	name := testName(used, method, path, op)

	// Path parameters are filled from the parameter schema's example when
	// there is one, and a schema-satisfying sample otherwise, so the URL is
	// syntactically valid. Semantically the id may not exist — a documented
	// 404 is an acceptable answer, and the allowed set includes it.
	url := path
	for _, p := range op.Parameters {
		rp := resolveParamRef(doc, p)
		if rp.In != "path" || rp.Name == "" {
			continue
		}
		v := mock.Sample(doc, rp.Schema, nil)
		if v == nil {
			v = "1"
		}
		url = strings.ReplaceAll(url, "{"+rp.Name+"}", fmt.Sprintf("%v", v))
	}

	var body []byte
	if op.RequestBody != nil {
		if media, ok := op.RequestBody.Content["application/json"]; ok && media.Schema != nil {
			body, _ = json.MarshalIndent(mock.Sample(doc, media.Schema, nil), "\t", "\t")
		}
	}

	var codes []int
	for code := range op.Responses {
		var n int
		if _, err := fmt.Sscanf(code, "%d", &n); err == nil {
			codes = append(codes, n)
		}
	}
	sort.Ints(codes)

	fmt.Fprintf(b, "\nfunc %s(t *testing.T) {\n", name)
	if body != nil {
		fmt.Fprintf(b, "\tbody := []byte(`%s`)\n", strings.ReplaceAll(string(body), "`", "'"))
	}
	fmt.Fprintf(b, "\tallowed := map[int]bool{")
	for i, c := range codes {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "%d: true", c)
	}
	b.WriteString("}\n")
	bodyArg := "nil"
	if body != nil {
		bodyArg = "body"
	}
	fmt.Fprintf(b, "\tdoJSON(t, %q, baseURL(t)+%q, %s, allowed)\n}\n",
		strings.ToUpper(method), url, bodyArg)
}

// testName builds a valid, unique Go test identifier from the operation.
func testName(used map[string]int, method, path string, op *core.Operation) string {
	base := op.OperationID
	if base == "" {
		base = method + " " + path
	}
	var b strings.Builder
	upper := true
	for _, r := range base {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			if upper && r >= 'a' && r <= 'z' {
				r -= 32
			}
			b.WriteRune(r)
			upper = false
		default:
			upper = true
		}
	}
	name := "Test" + b.String()
	used[name]++
	if n := used[name]; n > 1 {
		name = fmt.Sprintf("%s%d", name, n)
	}
	return name
}

func resolveParamRef(doc *core.Document, p core.Parameter) core.Parameter {
	if p.Ref == "" {
		return p
	}
	name := strings.TrimPrefix(p.Ref, "#/components/parameters/")
	if resolved, ok := doc.Components.Parameters[name]; ok && resolved != nil {
		return *resolved
	}
	return core.Parameter{}
}

func sortedPaths(doc *core.Document) []string {
	out := make([]string, 0, len(doc.Paths))
	for p := range doc.Paths {
		out = append(out, p)
	}
	sort.Strings(out)
	return out
}

var methodOrder = map[string]int{
	"get": 0, "post": 1, "put": 2, "patch": 3, "delete": 4, "head": 5, "options": 6,
}

func sortedMethods(ops map[string]*core.Operation) []string {
	out := make([]string, 0, len(ops))
	for m := range ops {
		out = append(out, m)
	}
	sort.Slice(out, func(i, j int) bool { return methodOrder[out[i]] < methodOrder[out[j]] })
	return out
}
