// Package shoppb's contents are generated by protoc. These tests do not
// verify logic — there is none to verify — they exercise the generated
// surface so a regenerated stub that no longer round-trips, or a service
// whose registration was dropped, fails here rather than at runtime.
package shoppb

import (
	"context"
	"errors"
	"net"
	"testing"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/credentials/insecure"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// ---- messages ----

// Every message must survive a marshal/unmarshal cycle with its fields, and
// its getters must report what was set.
func TestMessagesRoundTrip(t *testing.T) {
	cases := []struct {
		name string
		msg  proto.Message
		want func(t *testing.T, got proto.Message)
	}{
		{
			name: "Money",
			msg:  &Money{Amount: 12.5, Currency: "USD"},
			want: func(t *testing.T, got proto.Message) {
				m := got.(*Money)
				if m.GetAmount() != 12.5 || m.GetCurrency() != "USD" {
					t.Errorf("= %+v", m)
				}
			},
		},
		{
			name: "User",
			msg: &User{
				Id: 7, Name: "Ada", Email: "ada@example.com",
				Roles:    []string{"admin", "editor"},
				Metadata: map[string]string{"team": "core"},
			},
			want: func(t *testing.T, got proto.Message) {
				u := got.(*User)
				if u.GetId() != 7 || u.GetName() != "Ada" || u.GetEmail() != "ada@example.com" {
					t.Errorf("scalars = %+v", u)
				}
				if len(u.GetRoles()) != 2 {
					t.Errorf("roles = %v", u.GetRoles())
				}
				if u.GetMetadata()["team"] != "core" {
					t.Errorf("metadata = %v", u.GetMetadata())
				}
			},
		},
		{
			name: "GetUserRequest",
			msg:  &GetUserRequest{Id: 3},
			want: func(t *testing.T, got proto.Message) {
				if got.(*GetUserRequest).GetId() != 3 {
					t.Errorf("= %+v", got)
				}
			},
		},
		{
			name: "ListUsersRequest",
			msg:  &ListUsersRequest{Q: "ada", Limit: 10, Sort: "name"},
			want: func(t *testing.T, got proto.Message) {
				r := got.(*ListUsersRequest)
				if r.GetQ() != "ada" || r.GetLimit() != 10 || r.GetSort() != "name" {
					t.Errorf("= %+v", r)
				}
			},
		},
		{
			name: "ListUsersResponse",
			msg:  &ListUsersResponse{Users: []*User{{Id: 1}, {Id: 2}}, Total: 2},
			want: func(t *testing.T, got proto.Message) {
				r := got.(*ListUsersResponse)
				if len(r.GetUsers()) != 2 || r.GetTotal() != 2 {
					t.Errorf("= %+v", r)
				}
			},
		},
		{
			name: "CreateUserRequest",
			msg:  &CreateUserRequest{Name: "Grace", Email: "g@example.com", Roles: []string{"admin"}},
			want: func(t *testing.T, got proto.Message) {
				r := got.(*CreateUserRequest)
				if r.GetName() != "Grace" || r.GetEmail() != "g@example.com" || len(r.GetRoles()) != 1 {
					t.Errorf("= %+v", r)
				}
			},
		},
		{
			name: "DeleteUserRequest",
			msg:  &DeleteUserRequest{Id: 9},
			want: func(t *testing.T, got proto.Message) {
				if got.(*DeleteUserRequest).GetId() != 9 {
					t.Errorf("= %+v", got)
				}
			},
		},
		{
			name: "Empty",
			msg:  &Empty{},
			want: func(t *testing.T, got proto.Message) {},
		},
		{
			name: "Product",
			msg: &Product{
				Id: 1, Sku: "SKU-1", Title: "Widget",
				Price: &Money{Amount: 9.99, Currency: "EUR"},
			},
			want: func(t *testing.T, got proto.Message) {
				p := got.(*Product)
				if p.GetId() != 1 || p.GetSku() != "SKU-1" || p.GetTitle() != "Widget" {
					t.Errorf("scalars = %+v", p)
				}
				if p.GetPrice().GetCurrency() != "EUR" {
					t.Errorf("price = %+v", p.GetPrice())
				}
			},
		},
		{
			name: "ListProductsRequest",
			msg:  &ListProductsRequest{},
			want: func(t *testing.T, got proto.Message) {},
		},
		{
			name: "ListProductsResponse",
			msg:  &ListProductsResponse{Products: []*Product{{Id: 1}}},
			want: func(t *testing.T, got proto.Message) {
				if len(got.(*ListProductsResponse).GetProducts()) != 1 {
					t.Errorf("= %+v", got)
				}
			},
		},
		{
			name: "Order",
			msg:  &Order{Id: 5, Total: &Money{Amount: 1}},
			want: func(t *testing.T, got proto.Message) {
				o := got.(*Order)
				if o.GetId() != 5 || o.GetTotal().GetAmount() != 1 {
					t.Errorf("= %+v", o)
				}
			},
		},
		{
			name: "PlaceOrderRequest",
			msg:  &PlaceOrderRequest{},
			want: func(t *testing.T, got proto.Message) {},
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			wire, err := proto.Marshal(tc.msg)
			if err != nil {
				t.Fatalf("marshal: %v", err)
			}
			back := tc.msg.ProtoReflect().New().Interface()
			if err := proto.Unmarshal(wire, back); err != nil {
				t.Fatalf("unmarshal: %v", err)
			}
			if !proto.Equal(tc.msg, back) {
				t.Fatalf("round-trip changed the message:\n got %v\nwant %v", back, tc.msg)
			}
			tc.want(t, back)

			// The generated helpers must all be callable on a live message.
			if tc.msg.ProtoReflect().Descriptor() == nil {
				t.Error("nil descriptor")
			}
			_ = tc.msg.(interface{ String() string }).String()
			tc.msg.(interface{ Reset() }).Reset()
		})
	}
}

// Getters must be nil-safe: generated code returns zero values rather than
// panicking, which callers rely on.
func TestGettersOnNilMessages(t *testing.T) {
	var (
		money   *Money
		user    *User
		getReq  *GetUserRequest
		listReq *ListUsersRequest
		listRes *ListUsersResponse
		createR *CreateUserRequest
		delReq  *DeleteUserRequest
		product *Product
		prodRes *ListProductsResponse
		order   *Order
	)
	if money.GetAmount() != 0 || money.GetCurrency() != "" {
		t.Error("Money getters are not nil-safe")
	}
	if user.GetId() != 0 || user.GetName() != "" || user.GetEmail() != "" ||
		user.GetRoles() != nil || user.GetMetadata() != nil {
		t.Error("User getters are not nil-safe")
	}
	if getReq.GetId() != 0 {
		t.Error("GetUserRequest getter is not nil-safe")
	}
	if listReq.GetQ() != "" || listReq.GetLimit() != 0 || listReq.GetSort() != "" {
		t.Error("ListUsersRequest getters are not nil-safe")
	}
	if listRes.GetUsers() != nil || listRes.GetTotal() != 0 {
		t.Error("ListUsersResponse getters are not nil-safe")
	}
	if createR.GetName() != "" || createR.GetEmail() != "" || createR.GetRoles() != nil {
		t.Error("CreateUserRequest getters are not nil-safe")
	}
	if delReq.GetId() != 0 {
		t.Error("DeleteUserRequest getter is not nil-safe")
	}
	if product.GetId() != 0 || product.GetSku() != "" || product.GetTitle() != "" || product.GetPrice() != nil {
		t.Error("Product getters are not nil-safe")
	}
	if prodRes.GetProducts() != nil {
		t.Error("ListProductsResponse getter is not nil-safe")
	}
	if order.GetId() != 0 || order.GetTotal() != nil {
		t.Error("Order getters are not nil-safe")
	}
}

// The descriptor is what grpcurl and the console's reflection fallback read.
func TestFileDescriptorIsRegistered(t *testing.T) {
	d := (&User{}).ProtoReflect().Descriptor()
	if got := string(d.FullName()); got != "shop.v1.User" {
		t.Errorf("full name = %q, want shop.v1.User", got)
	}
	if got := string(d.ParentFile().Package()); got != "shop.v1" {
		t.Errorf("package = %q, want shop.v1", got)
	}
}

// ---- service ----

type testServer struct {
	UnimplementedUserServiceServer
	streamErr error
}

func (s *testServer) GetUser(ctx context.Context, r *GetUserRequest) (*User, error) {
	return &User{Id: r.GetId(), Name: "Ada"}, nil
}

func (s *testServer) ListUsers(ctx context.Context, r *ListUsersRequest) (*ListUsersResponse, error) {
	return &ListUsersResponse{Users: []*User{{Id: 1}}, Total: 1}, nil
}

func (s *testServer) CreateUser(ctx context.Context, r *CreateUserRequest) (*User, error) {
	return &User{Id: 99, Name: r.GetName()}, nil
}

func (s *testServer) DeleteUser(ctx context.Context, r *DeleteUserRequest) (*Empty, error) {
	return &Empty{}, nil
}

func (s *testServer) StreamUsers(r *ListUsersRequest, stream grpc.ServerStreamingServer[User]) error {
	if s.streamErr != nil {
		return s.streamErr
	}
	for _, u := range []*User{{Id: 1}, {Id: 2}} {
		if err := stream.Send(u); err != nil {
			return err
		}
	}
	return nil
}

// dial starts a server with srv registered and returns a connected client.
func dial(t *testing.T, srv UserServiceServer) UserServiceClient {
	t.Helper()
	lis, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatal(err)
	}
	s := grpc.NewServer()
	RegisterUserServiceServer(s, srv)
	go s.Serve(lis)
	t.Cleanup(s.Stop)

	cc, err := grpc.NewClient(lis.Addr().String(), grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { cc.Close() })
	return NewUserServiceClient(cc)
}

// Each generated client method must reach its registered handler.
func TestClientReachesServer(t *testing.T) {
	c := dial(t, &testServer{})
	ctx := context.Background()

	if got, err := c.GetUser(ctx, &GetUserRequest{Id: 4}); err != nil || got.GetId() != 4 {
		t.Errorf("GetUser = %v, %v", got, err)
	}
	if got, err := c.ListUsers(ctx, &ListUsersRequest{}); err != nil || got.GetTotal() != 1 {
		t.Errorf("ListUsers = %v, %v", got, err)
	}
	if got, err := c.CreateUser(ctx, &CreateUserRequest{Name: "Grace"}); err != nil || got.GetName() != "Grace" {
		t.Errorf("CreateUser = %v, %v", got, err)
	}
	if _, err := c.DeleteUser(ctx, &DeleteUserRequest{Id: 1}); err != nil {
		t.Errorf("DeleteUser: %v", err)
	}
}

func TestStreamUsersDeliversEveryMessage(t *testing.T) {
	c := dial(t, &testServer{})
	stream, err := c.StreamUsers(context.Background(), &ListUsersRequest{})
	if err != nil {
		t.Fatal(err)
	}
	count := 0
	for {
		_, err := stream.Recv()
		if err != nil {
			break
		}
		count++
	}
	if count != 2 {
		t.Errorf("received %d messages, want 2", count)
	}
}

// A handler error must arrive at the client as a status, not a dropped stream.
func TestStreamUsersPropagatesError(t *testing.T) {
	c := dial(t, &testServer{streamErr: status.Error(codes.Internal, "boom")})
	stream, err := c.StreamUsers(context.Background(), &ListUsersRequest{})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := stream.Recv(); err == nil {
		t.Fatal("expected an error from the stream")
	} else if status.Code(err) != codes.Internal {
		t.Errorf("code = %v, want Internal", status.Code(err))
	}
}

// The Unimplemented embed is what makes a partial server compile; every method
// must answer Unimplemented rather than panic.
func TestUnimplementedServerReturnsUnimplemented(t *testing.T) {
	c := dial(t, &UnimplementedUserServiceServer{})
	ctx := context.Background()

	calls := map[string]error{}
	_, calls["GetUser"] = c.GetUser(ctx, &GetUserRequest{})
	_, calls["ListUsers"] = c.ListUsers(ctx, &ListUsersRequest{})
	_, calls["CreateUser"] = c.CreateUser(ctx, &CreateUserRequest{})
	_, calls["DeleteUser"] = c.DeleteUser(ctx, &DeleteUserRequest{})

	for name, err := range calls {
		if status.Code(err) != codes.Unimplemented {
			t.Errorf("%s: code = %v, want Unimplemented", name, status.Code(err))
		}
	}

	stream, err := c.StreamUsers(ctx, &ListUsersRequest{})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := stream.Recv(); status.Code(err) != codes.Unimplemented {
		t.Errorf("StreamUsers: code = %v, want Unimplemented", status.Code(err))
	}
}

// The service descriptor drives registration and reflection.
func TestServiceDesc(t *testing.T) {
	if UserService_ServiceDesc.ServiceName != "shop.v1.UserService" {
		t.Errorf("service name = %q", UserService_ServiceDesc.ServiceName)
	}
	if len(UserService_ServiceDesc.Methods) != 4 {
		t.Errorf("unary methods = %d, want 4", len(UserService_ServiceDesc.Methods))
	}
	if len(UserService_ServiceDesc.Streams) != 1 {
		t.Errorf("streams = %d, want 1", len(UserService_ServiceDesc.Streams))
	}
}

// A request the server cannot decode must surface as an error, exercising the
// generated handlers' decode path.
func TestHandlerDecodeFailure(t *testing.T) {
	lis, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatal(err)
	}
	s := grpc.NewServer()
	RegisterUserServiceServer(s, &testServer{})
	go s.Serve(lis)
	defer s.Stop()

	cc, err := grpc.NewClient(lis.Addr().String(), grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		t.Fatal(err)
	}
	defer cc.Close()

	// Sending a message of the wrong shape makes the server-side decode fail.
	var out User
	err = cc.Invoke(context.Background(), "/shop.v1.UserService/GetUser", &badMessage{}, &out)
	if err == nil {
		t.Error("expected an error for an undecodable request")
	}
}

type badMessage struct{}

func (b *badMessage) Reset()         {}
func (b *badMessage) String() string { return "bad" }
func (b *badMessage) ProtoMessage()  {}

// Marshal always fails, which is what drives the error path.
func (b *badMessage) Marshal() ([]byte, error) { return nil, errors.New("cannot marshal") }

// ---- exhaustive generated surface ----

// allMessages is every message protoc emitted for shop.proto. Listing them
// explicitly means a message added to the .proto and regenerated but forgotten
// here shows up as a coverage gap.
func allMessages() []proto.Message {
	return []proto.Message{
		&Money{}, &User{}, &GetUserRequest{}, &ListUsersRequest{},
		&ListUsersResponse{}, &CreateUserRequest{}, &DeleteUserRequest{},
		&Empty{}, &Product{}, &GetProductRequest{}, &ListProductsRequest{},
		&ListProductsResponse{}, &Order{}, &GetOrderRequest{}, &PlaceOrderRequest{},
	}
}

// ProtoMessage and Descriptor are the marker and legacy accessors every
// generated type carries; they must be callable on all of them.
func TestGeneratedMarkersOnEveryMessage(t *testing.T) {
	for _, m := range allMessages() {
		name := string(m.ProtoReflect().Descriptor().FullName())
		t.Run(name, func(t *testing.T) {
			m.(interface{ ProtoMessage() }).ProtoMessage()

			raw, idx := m.(interface{ Descriptor() ([]byte, []int) }).Descriptor()
			if len(raw) == 0 {
				t.Error("empty raw descriptor")
			}
			if len(idx) == 0 {
				t.Error("empty descriptor index path")
			}

			// ProtoReflect must work on both a zero value and a populated one;
			// the generated code takes a different branch for each.
			if m.ProtoReflect().Descriptor() == nil {
				t.Error("nil descriptor via reflection")
			}
			if got := m.ProtoReflect().Interface(); got == nil {
				t.Error("nil message via reflection")
			}
		})
	}
}

// Getters not already exercised by the round-trip table, called on populated
// values so the field access itself runs.
func TestRemainingGetters(t *testing.T) {
	p := &Product{Sku: "S", Tags: []string{"a"}, InStock: true}
	if len(p.GetTags()) != 1 || !p.GetInStock() {
		t.Errorf("Product = %+v", p)
	}

	o := &Order{UserId: 3, Status: "PAID"}
	if o.GetUserId() != 3 || o.GetStatus() != "PAID" {
		t.Errorf("Order = %+v", o)
	}

	lpr := &ListProductsRequest{Q: "x", Limit: 5}
	if lpr.GetQ() != "x" || lpr.GetLimit() != 5 {
		t.Errorf("ListProductsRequest = %+v", lpr)
	}

	lpres := &ListProductsResponse{Total: 2}
	if lpres.GetTotal() != 2 {
		t.Errorf("ListProductsResponse = %+v", lpres)
	}

	if (&GetProductRequest{Id: 8}).GetId() != 8 {
		t.Error("GetProductRequest.GetId")
	}
	if (&GetOrderRequest{Id: 9}).GetId() != 9 {
		t.Error("GetOrderRequest.GetId")
	}

	por := &PlaceOrderRequest{UserId: 1, ProductIds: []int32{4, 5}}
	if por.GetUserId() != 1 || len(por.GetProductIds()) != 2 {
		t.Errorf("PlaceOrderRequest = %+v", por)
	}
}

// The same getters on nil receivers, completing the nil-safety sweep.
func TestRemainingGettersOnNil(t *testing.T) {
	var (
		product *Product
		order   *Order
		lpReq   *ListProductsRequest
		lpRes   *ListProductsResponse
		gpReq   *GetProductRequest
		goReq   *GetOrderRequest
		poReq   *PlaceOrderRequest
	)
	if product.GetTags() != nil || product.GetInStock() {
		t.Error("Product getters are not nil-safe")
	}
	if order.GetUserId() != 0 || order.GetStatus() != "" {
		t.Error("Order getters are not nil-safe")
	}
	if lpReq.GetQ() != "" || lpReq.GetLimit() != 0 {
		t.Error("ListProductsRequest getters are not nil-safe")
	}
	if lpRes.GetTotal() != 0 {
		t.Error("ListProductsResponse getter is not nil-safe")
	}
	if gpReq.GetId() != 0 || goReq.GetId() != 0 {
		t.Error("request id getters are not nil-safe")
	}
	if poReq.GetUserId() != 0 || poReq.GetProductIds() != nil {
		t.Error("PlaceOrderRequest getters are not nil-safe")
	}
}

// Every message must round-trip, including the ones not in the table above.
func TestEveryMessageRoundTrips(t *testing.T) {
	for _, m := range allMessages() {
		name := string(m.ProtoReflect().Descriptor().FullName())
		t.Run(name, func(t *testing.T) {
			wire, err := proto.Marshal(m)
			if err != nil {
				t.Fatalf("marshal: %v", err)
			}
			back := m.ProtoReflect().New().Interface()
			if err := proto.Unmarshal(wire, back); err != nil {
				t.Fatalf("unmarshal: %v", err)
			}
			if !proto.Equal(m, back) {
				t.Errorf("round-trip changed the message")
			}
			m.(interface{ Reset() }).Reset()
			_ = m.(interface{ String() string }).String()
		})
	}
}

// ProtoReflect takes a different path for a nil receiver, which is how the
// runtime obtains a zero message for a type.
func TestProtoReflectOnNilReceivers(t *testing.T) {
	nils := []proto.Message{
		(*Money)(nil), (*User)(nil), (*GetUserRequest)(nil), (*ListUsersRequest)(nil),
		(*ListUsersResponse)(nil), (*CreateUserRequest)(nil), (*DeleteUserRequest)(nil),
		(*Empty)(nil), (*Product)(nil), (*GetProductRequest)(nil), (*ListProductsRequest)(nil),
		(*ListProductsResponse)(nil), (*Order)(nil), (*GetOrderRequest)(nil), (*PlaceOrderRequest)(nil),
	}
	for _, m := range nils {
		rm := m.ProtoReflect()
		if rm == nil {
			t.Fatalf("%T: nil reflection message", m)
		}
		name := string(rm.Descriptor().FullName())
		if name == "" {
			t.Errorf("%T: empty descriptor name", m)
		}
		if rm.IsValid() {
			t.Errorf("%s: a nil receiver should not report valid", name)
		}
	}
}

// ---- ProductService and OrderService ----

type testProductServer struct {
	UnimplementedProductServiceServer
}

func (s *testProductServer) GetProduct(ctx context.Context, r *GetProductRequest) (*Product, error) {
	return &Product{Id: r.GetId(), Sku: "SKU"}, nil
}

func (s *testProductServer) ListProducts(ctx context.Context, r *ListProductsRequest) (*ListProductsResponse, error) {
	return &ListProductsResponse{Products: []*Product{{Id: 1}}, Total: 1}, nil
}

func (s *testProductServer) WatchProducts(r *ListProductsRequest, stream grpc.ServerStreamingServer[Product]) error {
	return stream.Send(&Product{Id: 1})
}

type testOrderServer struct {
	UnimplementedOrderServiceServer
}

func (s *testOrderServer) PlaceOrder(ctx context.Context, r *PlaceOrderRequest) (*Order, error) {
	return &Order{Id: 1, UserId: r.GetUserId()}, nil
}

func (s *testOrderServer) GetOrder(ctx context.Context, r *GetOrderRequest) (*Order, error) {
	return &Order{Id: r.GetId()}, nil
}

// serve registers whatever the caller binds and returns the connection, so all
// three services share one setup path.
func serve(t *testing.T, register func(s grpc.ServiceRegistrar)) *grpc.ClientConn {
	t.Helper()
	lis, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatal(err)
	}
	s := grpc.NewServer()
	register(s)
	go s.Serve(lis)
	t.Cleanup(s.Stop)

	cc, err := grpc.NewClient(lis.Addr().String(), grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { cc.Close() })
	return cc
}

func TestProductServiceRoundTrip(t *testing.T) {
	cc := serve(t, func(s grpc.ServiceRegistrar) {
		RegisterProductServiceServer(s, &testProductServer{})
	})
	c := NewProductServiceClient(cc)
	ctx := context.Background()

	if got, err := c.GetProduct(ctx, &GetProductRequest{Id: 5}); err != nil || got.GetId() != 5 {
		t.Errorf("GetProduct = %v, %v", got, err)
	}
	if got, err := c.ListProducts(ctx, &ListProductsRequest{}); err != nil || got.GetTotal() != 1 {
		t.Errorf("ListProducts = %v, %v", got, err)
	}

	stream, err := c.WatchProducts(ctx, &ListProductsRequest{})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := stream.Recv(); err != nil {
		t.Errorf("WatchProducts: %v", err)
	}
}

func TestOrderServiceRoundTrip(t *testing.T) {
	cc := serve(t, func(s grpc.ServiceRegistrar) {
		RegisterOrderServiceServer(s, &testOrderServer{})
	})
	c := NewOrderServiceClient(cc)
	ctx := context.Background()

	if got, err := c.PlaceOrder(ctx, &PlaceOrderRequest{UserId: 3}); err != nil || got.GetUserId() != 3 {
		t.Errorf("PlaceOrder = %v, %v", got, err)
	}
	if got, err := c.GetOrder(ctx, &GetOrderRequest{Id: 8}); err != nil || got.GetId() != 8 {
		t.Errorf("GetOrder = %v, %v", got, err)
	}
}

// The Unimplemented embeds for the other two services must answer the same way.
func TestOtherServicesUnimplemented(t *testing.T) {
	pcc := serve(t, func(s grpc.ServiceRegistrar) {
		RegisterProductServiceServer(s, &UnimplementedProductServiceServer{})
	})
	pc := NewProductServiceClient(pcc)
	ctx := context.Background()

	if _, err := pc.GetProduct(ctx, &GetProductRequest{}); status.Code(err) != codes.Unimplemented {
		t.Errorf("GetProduct: code = %v, want Unimplemented", status.Code(err))
	}
	if _, err := pc.ListProducts(ctx, &ListProductsRequest{}); status.Code(err) != codes.Unimplemented {
		t.Errorf("ListProducts: code = %v, want Unimplemented", status.Code(err))
	}
	if stream, err := pc.WatchProducts(ctx, &ListProductsRequest{}); err == nil {
		if _, err := stream.Recv(); status.Code(err) != codes.Unimplemented {
			t.Errorf("WatchProducts: code = %v, want Unimplemented", status.Code(err))
		}
	}

	occ := serve(t, func(s grpc.ServiceRegistrar) {
		RegisterOrderServiceServer(s, &UnimplementedOrderServiceServer{})
	})
	oc := NewOrderServiceClient(occ)
	if _, err := oc.PlaceOrder(ctx, &PlaceOrderRequest{}); status.Code(err) != codes.Unimplemented {
		t.Errorf("PlaceOrder: code = %v, want Unimplemented", status.Code(err))
	}
	if _, err := oc.GetOrder(ctx, &GetOrderRequest{}); status.Code(err) != codes.Unimplemented {
		t.Errorf("GetOrder: code = %v, want Unimplemented", status.Code(err))
	}
}

func TestAllServiceDescs(t *testing.T) {
	cases := []struct {
		desc    grpc.ServiceDesc
		name    string
		methods int
		streams int
	}{
		{UserService_ServiceDesc, "shop.v1.UserService", 4, 1},
		{ProductService_ServiceDesc, "shop.v1.ProductService", 2, 1},
		{OrderService_ServiceDesc, "shop.v1.OrderService", 2, 0},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if tc.desc.ServiceName != tc.name {
				t.Errorf("name = %q, want %q", tc.desc.ServiceName, tc.name)
			}
			if len(tc.desc.Methods) != tc.methods {
				t.Errorf("methods = %d, want %d", len(tc.desc.Methods), tc.methods)
			}
			if len(tc.desc.Streams) != tc.streams {
				t.Errorf("streams = %d, want %d", len(tc.desc.Streams), tc.streams)
			}
		})
	}
}

// Each generated handler has two paths: a direct call when no interceptor is
// installed, and a wrapped one when there is. Both must reach the service.
func TestHandlersRunUnderInterceptors(t *testing.T) {
	var unaryCalls, streamCalls int

	lis, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatal(err)
	}
	s := grpc.NewServer(
		grpc.UnaryInterceptor(func(ctx context.Context, req any, info *grpc.UnaryServerInfo, h grpc.UnaryHandler) (any, error) {
			unaryCalls++
			return h(ctx, req)
		}),
		grpc.StreamInterceptor(func(srv any, ss grpc.ServerStream, info *grpc.StreamServerInfo, h grpc.StreamHandler) error {
			streamCalls++
			return h(srv, ss)
		}),
	)
	RegisterUserServiceServer(s, &testServer{})
	RegisterProductServiceServer(s, &testProductServer{})
	RegisterOrderServiceServer(s, &testOrderServer{})
	go s.Serve(lis)
	defer s.Stop()

	cc, err := grpc.NewClient(lis.Addr().String(), grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		t.Fatal(err)
	}
	defer cc.Close()
	ctx := context.Background()

	uc := NewUserServiceClient(cc)
	if _, err := uc.GetUser(ctx, &GetUserRequest{Id: 1}); err != nil {
		t.Errorf("GetUser: %v", err)
	}
	if _, err := uc.ListUsers(ctx, &ListUsersRequest{}); err != nil {
		t.Errorf("ListUsers: %v", err)
	}
	if _, err := uc.CreateUser(ctx, &CreateUserRequest{}); err != nil {
		t.Errorf("CreateUser: %v", err)
	}
	if _, err := uc.DeleteUser(ctx, &DeleteUserRequest{}); err != nil {
		t.Errorf("DeleteUser: %v", err)
	}

	pc := NewProductServiceClient(cc)
	if _, err := pc.GetProduct(ctx, &GetProductRequest{}); err != nil {
		t.Errorf("GetProduct: %v", err)
	}
	if _, err := pc.ListProducts(ctx, &ListProductsRequest{}); err != nil {
		t.Errorf("ListProducts: %v", err)
	}

	oc := NewOrderServiceClient(cc)
	if _, err := oc.PlaceOrder(ctx, &PlaceOrderRequest{}); err != nil {
		t.Errorf("PlaceOrder: %v", err)
	}
	if _, err := oc.GetOrder(ctx, &GetOrderRequest{}); err != nil {
		t.Errorf("GetOrder: %v", err)
	}

	// Streaming handlers go through the stream interceptor instead.
	if st, err := uc.StreamUsers(ctx, &ListUsersRequest{}); err != nil {
		t.Errorf("StreamUsers: %v", err)
	} else {
		for {
			if _, err := st.Recv(); err != nil {
				break
			}
		}
	}
	if st, err := pc.WatchProducts(ctx, &ListProductsRequest{}); err != nil {
		t.Errorf("WatchProducts: %v", err)
	} else {
		for {
			if _, err := st.Recv(); err != nil {
				break
			}
		}
	}

	if unaryCalls != 8 {
		t.Errorf("unary interceptor ran %d times, want 8", unaryCalls)
	}
	if streamCalls != 2 {
		t.Errorf("stream interceptor ran %d times, want 2", streamCalls)
	}
}
